// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: mnemosyne/v1/health.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_mnemosyne_v1_health_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_health_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_health_proto_rawDescGZIP(), []int{0}
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     *Namespace             `protobuf:"bytes,1,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"` // Filter stats by namespace
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_mnemosyne_v1_health_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_health_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_health_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatsRequest) GetNamespace() *Namespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *Stats                 `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_mnemosyne_v1_health_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_health_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_health_proto_rawDescGZIP(), []int{2}
}

func (x *GetStatsResponse) GetStats() *Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type GetMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	mi := &file_mnemosyne_v1_health_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_health_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsRequest.ProtoReflect.Descriptor instead.
func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_health_proto_rawDescGZIP(), []int{3}
}

type GetMetricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       *Metrics               `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	mi := &file_mnemosyne_v1_health_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_health_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMetricsResponse.ProtoReflect.Descriptor instead.
func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_health_proto_rawDescGZIP(), []int{4}
}

func (x *GetMetricsResponse) GetMetrics() *Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type GetMemoryUsageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemoryUsageRequest) Reset() {
	*x = GetMemoryUsageRequest{}
	mi := &file_mnemosyne_v1_health_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemoryUsageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemoryUsageRequest) ProtoMessage() {}

func (x *GetMemoryUsageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_health_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemoryUsageRequest.ProtoReflect.Descriptor instead.
func (*GetMemoryUsageRequest) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_health_proto_rawDescGZIP(), []int{5}
}

type GetMemoryUsageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RssBytes      uint64                 `protobuf:"varint,1,opt,name=rss_bytes,json=rssBytes,proto3" json:"rss_bytes,omitempty"`            // Resident set size
	HeapBytes     uint64                 `protobuf:"varint,2,opt,name=heap_bytes,json=heapBytes,proto3" json:"heap_bytes,omitempty"`         // Heap allocation
	DbSizeBytes   uint64                 `protobuf:"varint,3,opt,name=db_size_bytes,json=dbSizeBytes,proto3" json:"db_size_bytes,omitempty"` // Database file size
	CacheBytes    uint64                 `protobuf:"varint,4,opt,name=cache_bytes,json=cacheBytes,proto3" json:"cache_bytes,omitempty"`      // In-memory cache size
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemoryUsageResponse) Reset() {
	*x = GetMemoryUsageResponse{}
	mi := &file_mnemosyne_v1_health_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemoryUsageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemoryUsageResponse) ProtoMessage() {}

func (x *GetMemoryUsageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_health_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemoryUsageResponse.ProtoReflect.Descriptor instead.
func (*GetMemoryUsageResponse) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_health_proto_rawDescGZIP(), []int{6}
}

func (x *GetMemoryUsageResponse) GetRssBytes() uint64 {
	if x != nil {
		return x.RssBytes
	}
	return 0
}

func (x *GetMemoryUsageResponse) GetHeapBytes() uint64 {
	if x != nil {
		return x.HeapBytes
	}
	return 0
}

func (x *GetMemoryUsageResponse) GetDbSizeBytes() uint64 {
	if x != nil {
		return x.DbSizeBytes
	}
	return 0
}

func (x *GetMemoryUsageResponse) GetCacheBytes() uint64 {
	if x != nil {
		return x.CacheBytes
	}
	return 0
}

type StreamMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IntervalMs    uint32                 `protobuf:"varint,1,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"` // Default: 1000 (1 second)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMetricsRequest) Reset() {
	*x = StreamMetricsRequest{}
	mi := &file_mnemosyne_v1_health_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMetricsRequest) ProtoMessage() {}

func (x *StreamMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_health_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMetricsRequest.ProtoReflect.Descriptor instead.
func (*StreamMetricsRequest) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_health_proto_rawDescGZIP(), []int{7}
}

func (x *StreamMetricsRequest) GetIntervalMs() uint32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

type MetricsSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     uint64                 `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp
	Metrics       *Metrics               `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsSnapshot) Reset() {
	*x = MetricsSnapshot{}
	mi := &file_mnemosyne_v1_health_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsSnapshot) ProtoMessage() {}

func (x *MetricsSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_health_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsSnapshot.ProtoReflect.Descriptor instead.
func (*MetricsSnapshot) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_health_proto_rawDescGZIP(), []int{8}
}

func (x *MetricsSnapshot) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *MetricsSnapshot) GetMetrics() *Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_mnemosyne_v1_health_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_health_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_health_proto_rawDescGZIP(), []int{9}
}

type GetVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`                         // Semantic version (e.g., "2.2.0")
	ApiVersion    string                 `protobuf:"bytes,2,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"` // API package version (e.g., "v1")
	Features      []string               `protobuf:"bytes,3,rep,name=features,proto3" json:"features,omitempty"`                       // Enabled features ("streaming", "auth", etc.)
	BuildTime     string                 `protobuf:"bytes,4,opt,name=build_time,json=buildTime,proto3" json:"build_time,omitempty"`    // ISO 8601 timestamp
	GitCommit     string                 `protobuf:"bytes,5,opt,name=git_commit,json=gitCommit,proto3" json:"git_commit,omitempty"`    // Git commit hash
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_mnemosyne_v1_health_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_health_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_health_proto_rawDescGZIP(), []int{10}
}

func (x *GetVersionResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetVersionResponse) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *GetVersionResponse) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *GetVersionResponse) GetBuildTime() string {
	if x != nil {
		return x.BuildTime
	}
	return ""
}

func (x *GetVersionResponse) GetGitCommit() string {
	if x != nil {
		return x.GitCommit
	}
	return ""
}

var File_mnemosyne_v1_health_proto protoreflect.FileDescriptor

const file_mnemosyne_v1_health_proto_rawDesc = "" +
	"\n" +
	"\x19mnemosyne/v1/health.proto\x12\fmnemosyne.v1\x1a\x18mnemosyne/v1/types.proto\"\x14\n" +
	"\x12HealthCheckRequest\"[\n" +
	"\x0fGetStatsRequest\x12:\n" +
	"\tnamespace\x18\x01 \x01(\v2\x17.mnemosyne.v1.NamespaceH\x00R\tnamespace\x88\x01\x01B\f\n" +
	"\n" +
	"_namespace\"=\n" +
	"\x10GetStatsResponse\x12)\n" +
	"\x05stats\x18\x01 \x01(\v2\x13.mnemosyne.v1.StatsR\x05stats\"\x13\n" +
	"\x11GetMetricsRequest\"E\n" +
	"\x12GetMetricsResponse\x12/\n" +
	"\ametrics\x18\x01 \x01(\v2\x15.mnemosyne.v1.MetricsR\ametrics\"\x17\n" +
	"\x15GetMemoryUsageRequest\"\x99\x01\n" +
	"\x16GetMemoryUsageResponse\x12\x1b\n" +
	"\trss_bytes\x18\x01 \x01(\x04R\brssBytes\x12\x1d\n" +
	"\n" +
	"heap_bytes\x18\x02 \x01(\x04R\theapBytes\x12\"\n" +
	"\rdb_size_bytes\x18\x03 \x01(\x04R\vdbSizeBytes\x12\x1f\n" +
	"\vcache_bytes\x18\x04 \x01(\x04R\n" +
	"cacheBytes\"7\n" +
	"\x14StreamMetricsRequest\x12\x1f\n" +
	"\vinterval_ms\x18\x01 \x01(\rR\n" +
	"intervalMs\"`\n" +
	"\x0fMetricsSnapshot\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x04R\ttimestamp\x12/\n" +
	"\ametrics\x18\x02 \x01(\v2\x15.mnemosyne.v1.MetricsR\ametrics\"\x13\n" +
	"\x11GetVersionRequest\"\xa9\x01\n" +
	"\x12GetVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1f\n" +
	"\vapi_version\x18\x02 \x01(\tR\n" +
	"apiVersion\x12\x1a\n" +
	"\bfeatures\x18\x03 \x03(\tR\bfeatures\x12\x1d\n" +
	"\n" +
	"build_time\x18\x04 \x01(\tR\tbuildTime\x12\x1d\n" +
	"\n" +
	"git_commit\x18\x05 \x01(\tR\tgitCommit2\x83\x04\n" +
	"\rHealthService\x12R\n" +
	"\vHealthCheck\x12 .mnemosyne.v1.HealthCheckRequest\x1a!.mnemosyne.v1.HealthCheckResponse\x12I\n" +
	"\bGetStats\x12\x1d.mnemosyne.v1.GetStatsRequest\x1a\x1e.mnemosyne.v1.GetStatsResponse\x12O\n" +
	"\n" +
	"GetMetrics\x12\x1f.mnemosyne.v1.GetMetricsRequest\x1a .mnemosyne.v1.GetMetricsResponse\x12[\n" +
	"\x0eGetMemoryUsage\x12#.mnemosyne.v1.GetMemoryUsageRequest\x1a$.mnemosyne.v1.GetMemoryUsageResponse\x12T\n" +
	"\rStreamMetrics\x12\".mnemosyne.v1.StreamMetricsRequest\x1a\x1d.mnemosyne.v1.MetricsSnapshot0\x01\x12O\n" +
	"\n" +
	"GetVersion\x12\x1f.mnemosyne.v1.GetVersionRequest\x1a .mnemosyne.v1.GetVersionResponseB6Z4github.com/rand/pedantic-raven/internal/mnemosyne/pbb\x06proto3"

var (
	file_mnemosyne_v1_health_proto_rawDescOnce sync.Once
	file_mnemosyne_v1_health_proto_rawDescData []byte
)

func file_mnemosyne_v1_health_proto_rawDescGZIP() []byte {
	file_mnemosyne_v1_health_proto_rawDescOnce.Do(func() {
		file_mnemosyne_v1_health_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mnemosyne_v1_health_proto_rawDesc), len(file_mnemosyne_v1_health_proto_rawDesc)))
	})
	return file_mnemosyne_v1_health_proto_rawDescData
}

var file_mnemosyne_v1_health_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_mnemosyne_v1_health_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),     // 0: mnemosyne.v1.HealthCheckRequest
	(*GetStatsRequest)(nil),        // 1: mnemosyne.v1.GetStatsRequest
	(*GetStatsResponse)(nil),       // 2: mnemosyne.v1.GetStatsResponse
	(*GetMetricsRequest)(nil),      // 3: mnemosyne.v1.GetMetricsRequest
	(*GetMetricsResponse)(nil),     // 4: mnemosyne.v1.GetMetricsResponse
	(*GetMemoryUsageRequest)(nil),  // 5: mnemosyne.v1.GetMemoryUsageRequest
	(*GetMemoryUsageResponse)(nil), // 6: mnemosyne.v1.GetMemoryUsageResponse
	(*StreamMetricsRequest)(nil),   // 7: mnemosyne.v1.StreamMetricsRequest
	(*MetricsSnapshot)(nil),        // 8: mnemosyne.v1.MetricsSnapshot
	(*GetVersionRequest)(nil),      // 9: mnemosyne.v1.GetVersionRequest
	(*GetVersionResponse)(nil),     // 10: mnemosyne.v1.GetVersionResponse
	(*Namespace)(nil),              // 11: mnemosyne.v1.Namespace
	(*Stats)(nil),                  // 12: mnemosyne.v1.Stats
	(*Metrics)(nil),                // 13: mnemosyne.v1.Metrics
	(*HealthCheckResponse)(nil),    // 14: mnemosyne.v1.HealthCheckResponse
}
var file_mnemosyne_v1_health_proto_depIdxs = []int32{
	11, // 0: mnemosyne.v1.GetStatsRequest.namespace:type_name -> mnemosyne.v1.Namespace
	12, // 1: mnemosyne.v1.GetStatsResponse.stats:type_name -> mnemosyne.v1.Stats
	13, // 2: mnemosyne.v1.GetMetricsResponse.metrics:type_name -> mnemosyne.v1.Metrics
	13, // 3: mnemosyne.v1.MetricsSnapshot.metrics:type_name -> mnemosyne.v1.Metrics
	0,  // 4: mnemosyne.v1.HealthService.HealthCheck:input_type -> mnemosyne.v1.HealthCheckRequest
	1,  // 5: mnemosyne.v1.HealthService.GetStats:input_type -> mnemosyne.v1.GetStatsRequest
	3,  // 6: mnemosyne.v1.HealthService.GetMetrics:input_type -> mnemosyne.v1.GetMetricsRequest
	5,  // 7: mnemosyne.v1.HealthService.GetMemoryUsage:input_type -> mnemosyne.v1.GetMemoryUsageRequest
	7,  // 8: mnemosyne.v1.HealthService.StreamMetrics:input_type -> mnemosyne.v1.StreamMetricsRequest
	9,  // 9: mnemosyne.v1.HealthService.GetVersion:input_type -> mnemosyne.v1.GetVersionRequest
	14, // 10: mnemosyne.v1.HealthService.HealthCheck:output_type -> mnemosyne.v1.HealthCheckResponse
	2,  // 11: mnemosyne.v1.HealthService.GetStats:output_type -> mnemosyne.v1.GetStatsResponse
	4,  // 12: mnemosyne.v1.HealthService.GetMetrics:output_type -> mnemosyne.v1.GetMetricsResponse
	6,  // 13: mnemosyne.v1.HealthService.GetMemoryUsage:output_type -> mnemosyne.v1.GetMemoryUsageResponse
	8,  // 14: mnemosyne.v1.HealthService.StreamMetrics:output_type -> mnemosyne.v1.MetricsSnapshot
	10, // 15: mnemosyne.v1.HealthService.GetVersion:output_type -> mnemosyne.v1.GetVersionResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_mnemosyne_v1_health_proto_init() }
func file_mnemosyne_v1_health_proto_init() {
	if File_mnemosyne_v1_health_proto != nil {
		return
	}
	file_mnemosyne_v1_types_proto_init()
	file_mnemosyne_v1_health_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mnemosyne_v1_health_proto_rawDesc), len(file_mnemosyne_v1_health_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mnemosyne_v1_health_proto_goTypes,
		DependencyIndexes: file_mnemosyne_v1_health_proto_depIdxs,
		MessageInfos:      file_mnemosyne_v1_health_proto_msgTypes,
	}.Build()
	File_mnemosyne_v1_health_proto = out.File
	file_mnemosyne_v1_health_proto_goTypes = nil
	file_mnemosyne_v1_health_proto_depIdxs = nil
}
