// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: mnemosyne/v1/memory.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreMemoryRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Content           string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`                                                             // Required: memory content
	Namespace         *Namespace             `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`                                                         // Required: organization
	Importance        *uint32                `protobuf:"varint,3,opt,name=importance,proto3,oneof" json:"importance,omitempty"`                                                // 1-10, if not provided LLM will determine
	Context           *string                `protobuf:"bytes,4,opt,name=context,proto3,oneof" json:"context,omitempty"`                                                       // Additional context
	Tags              []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`                                                                   // User-defined tags
	MemoryType        *MemoryType            `protobuf:"varint,6,opt,name=memory_type,json=memoryType,proto3,enum=mnemosyne.v1.MemoryType,oneof" json:"memory_type,omitempty"` // If not provided, LLM will classify
	SkipLlmEnrichment bool                   `protobuf:"varint,7,opt,name=skip_llm_enrichment,json=skipLlmEnrichment,proto3" json:"skip_llm_enrichment,omitempty"`             // Skip LLM processing (faster, less accurate)
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StoreMemoryRequest) Reset() {
	*x = StoreMemoryRequest{}
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreMemoryRequest) ProtoMessage() {}

func (x *StoreMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreMemoryRequest.ProtoReflect.Descriptor instead.
func (*StoreMemoryRequest) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_memory_proto_rawDescGZIP(), []int{0}
}

func (x *StoreMemoryRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *StoreMemoryRequest) GetNamespace() *Namespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *StoreMemoryRequest) GetImportance() uint32 {
	if x != nil && x.Importance != nil {
		return *x.Importance
	}
	return 0
}

func (x *StoreMemoryRequest) GetContext() string {
	if x != nil && x.Context != nil {
		return *x.Context
	}
	return ""
}

func (x *StoreMemoryRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *StoreMemoryRequest) GetMemoryType() MemoryType {
	if x != nil && x.MemoryType != nil {
		return *x.MemoryType
	}
	return MemoryType_MEMORY_TYPE_UNSPECIFIED
}

func (x *StoreMemoryRequest) GetSkipLlmEnrichment() bool {
	if x != nil {
		return x.SkipLlmEnrichment
	}
	return false
}

type StoreMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryId      string                 `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"` // Created memory ID
	Memory        *MemoryNote            `protobuf:"bytes,2,opt,name=memory,proto3" json:"memory,omitempty"`                     // Full memory with enrichment
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreMemoryResponse) Reset() {
	*x = StoreMemoryResponse{}
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreMemoryResponse) ProtoMessage() {}

func (x *StoreMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreMemoryResponse.ProtoReflect.Descriptor instead.
func (*StoreMemoryResponse) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_memory_proto_rawDescGZIP(), []int{1}
}

func (x *StoreMemoryResponse) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *StoreMemoryResponse) GetMemory() *MemoryNote {
	if x != nil {
		return x.Memory
	}
	return nil
}

type StoreMemoryProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`                             // "enriching", "embedding", "indexing", "complete"
	Percent       uint32                 `protobuf:"varint,2,opt,name=percent,proto3" json:"percent,omitempty"`                        // 0-100
	MemoryId      *string                `protobuf:"bytes,3,opt,name=memory_id,json=memoryId,proto3,oneof" json:"memory_id,omitempty"` // Available when complete
	Memory        *MemoryNote            `protobuf:"bytes,4,opt,name=memory,proto3,oneof" json:"memory,omitempty"`                     // Available when complete
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreMemoryProgress) Reset() {
	*x = StoreMemoryProgress{}
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreMemoryProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreMemoryProgress) ProtoMessage() {}

func (x *StoreMemoryProgress) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreMemoryProgress.ProtoReflect.Descriptor instead.
func (*StoreMemoryProgress) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_memory_proto_rawDescGZIP(), []int{2}
}

func (x *StoreMemoryProgress) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *StoreMemoryProgress) GetPercent() uint32 {
	if x != nil {
		return x.Percent
	}
	return 0
}

func (x *StoreMemoryProgress) GetMemoryId() string {
	if x != nil && x.MemoryId != nil {
		return *x.MemoryId
	}
	return ""
}

func (x *StoreMemoryProgress) GetMemory() *MemoryNote {
	if x != nil {
		return x.Memory
	}
	return nil
}

type GetMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryId      string                 `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemoryRequest) Reset() {
	*x = GetMemoryRequest{}
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemoryRequest) ProtoMessage() {}

func (x *GetMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemoryRequest.ProtoReflect.Descriptor instead.
func (*GetMemoryRequest) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_memory_proto_rawDescGZIP(), []int{3}
}

func (x *GetMemoryRequest) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

type GetMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memory        *MemoryNote            `protobuf:"bytes,1,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemoryResponse) Reset() {
	*x = GetMemoryResponse{}
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemoryResponse) ProtoMessage() {}

func (x *GetMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemoryResponse.ProtoReflect.Descriptor instead.
func (*GetMemoryResponse) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_memory_proto_rawDescGZIP(), []int{4}
}

func (x *GetMemoryResponse) GetMemory() *MemoryNote {
	if x != nil {
		return x.Memory
	}
	return nil
}

type UpdateMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryId      string                 `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	Content       *string                `protobuf:"bytes,2,opt,name=content,proto3,oneof" json:"content,omitempty"` // If set, triggers re-embedding
	Importance    *uint32                `protobuf:"varint,3,opt,name=importance,proto3,oneof" json:"importance,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`                               // Replaces existing tags
	AddTags       []string               `protobuf:"bytes,5,rep,name=add_tags,json=addTags,proto3" json:"add_tags,omitempty"`          // Appends to existing tags
	RemoveTags    []string               `protobuf:"bytes,6,rep,name=remove_tags,json=removeTags,proto3" json:"remove_tags,omitempty"` // Removes from existing tags
	ReEnrich      bool                   `protobuf:"varint,7,opt,name=re_enrich,json=reEnrich,proto3" json:"re_enrich,omitempty"`      // Force LLM re-enrichment
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemoryRequest) Reset() {
	*x = UpdateMemoryRequest{}
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemoryRequest) ProtoMessage() {}

func (x *UpdateMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateMemoryRequest) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_memory_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateMemoryRequest) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *UpdateMemoryRequest) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *UpdateMemoryRequest) GetImportance() uint32 {
	if x != nil && x.Importance != nil {
		return *x.Importance
	}
	return 0
}

func (x *UpdateMemoryRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateMemoryRequest) GetAddTags() []string {
	if x != nil {
		return x.AddTags
	}
	return nil
}

func (x *UpdateMemoryRequest) GetRemoveTags() []string {
	if x != nil {
		return x.RemoveTags
	}
	return nil
}

func (x *UpdateMemoryRequest) GetReEnrich() bool {
	if x != nil {
		return x.ReEnrich
	}
	return false
}

type UpdateMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memory        *MemoryNote            `protobuf:"bytes,1,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemoryResponse) Reset() {
	*x = UpdateMemoryResponse{}
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemoryResponse) ProtoMessage() {}

func (x *UpdateMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemoryResponse.ProtoReflect.Descriptor instead.
func (*UpdateMemoryResponse) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_memory_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMemoryResponse) GetMemory() *MemoryNote {
	if x != nil {
		return x.Memory
	}
	return nil
}

type DeleteMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryId      string                 `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMemoryRequest) Reset() {
	*x = DeleteMemoryRequest{}
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemoryRequest) ProtoMessage() {}

func (x *DeleteMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteMemoryRequest) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_memory_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteMemoryRequest) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

type DeleteMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMemoryResponse) Reset() {
	*x = DeleteMemoryResponse{}
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemoryResponse) ProtoMessage() {}

func (x *DeleteMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteMemoryResponse) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_memory_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteMemoryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListMemoriesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Namespace       *Namespace             `protobuf:"bytes,1,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	Limit           uint32                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`                                                                    // Default: 20, max: 1000
	Offset          *uint32                `protobuf:"varint,3,opt,name=offset,proto3,oneof" json:"offset,omitempty"`                                                            // For pagination
	MemoryTypes     []MemoryType           `protobuf:"varint,4,rep,packed,name=memory_types,json=memoryTypes,proto3,enum=mnemosyne.v1.MemoryType" json:"memory_types,omitempty"` // Filter by type (OR logic)
	Tags            []string               `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`                                                                       // Filter by tags (AND logic)
	MinImportance   *uint32                `protobuf:"varint,6,opt,name=min_importance,json=minImportance,proto3,oneof" json:"min_importance,omitempty"`
	IncludeArchived bool                   `protobuf:"varint,7,opt,name=include_archived,json=includeArchived,proto3" json:"include_archived,omitempty"`
	SortBy          string                 `protobuf:"bytes,8,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`        // "created_at", "updated_at", "importance", "access_count"
	SortDesc        bool                   `protobuf:"varint,9,opt,name=sort_desc,json=sortDesc,proto3" json:"sort_desc,omitempty"` // Descending order
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListMemoriesRequest) Reset() {
	*x = ListMemoriesRequest{}
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMemoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMemoriesRequest) ProtoMessage() {}

func (x *ListMemoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMemoriesRequest.ProtoReflect.Descriptor instead.
func (*ListMemoriesRequest) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_memory_proto_rawDescGZIP(), []int{9}
}

func (x *ListMemoriesRequest) GetNamespace() *Namespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *ListMemoriesRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMemoriesRequest) GetOffset() uint32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *ListMemoriesRequest) GetMemoryTypes() []MemoryType {
	if x != nil {
		return x.MemoryTypes
	}
	return nil
}

func (x *ListMemoriesRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ListMemoriesRequest) GetMinImportance() uint32 {
	if x != nil && x.MinImportance != nil {
		return *x.MinImportance
	}
	return 0
}

func (x *ListMemoriesRequest) GetIncludeArchived() bool {
	if x != nil {
		return x.IncludeArchived
	}
	return false
}

func (x *ListMemoriesRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListMemoriesRequest) GetSortDesc() bool {
	if x != nil {
		return x.SortDesc
	}
	return false
}

type ListMemoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memories      []*MemoryNote          `protobuf:"bytes,1,rep,name=memories,proto3" json:"memories,omitempty"`
	TotalCount    uint32                 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"` // Total matching (for pagination)
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`          // Whether more results exist
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMemoriesResponse) Reset() {
	*x = ListMemoriesResponse{}
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMemoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMemoriesResponse) ProtoMessage() {}

func (x *ListMemoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMemoriesResponse.ProtoReflect.Descriptor instead.
func (*ListMemoriesResponse) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_memory_proto_rawDescGZIP(), []int{10}
}

func (x *ListMemoriesResponse) GetMemories() []*MemoryNote {
	if x != nil {
		return x.Memories
	}
	return nil
}

func (x *ListMemoriesResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListMemoriesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type RecallRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Query           string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"` // Required: search query
	Namespace       *Namespace             `protobuf:"bytes,2,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	MaxResults      uint32                 `protobuf:"varint,3,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"` // Default: 10
	MinImportance   *uint32                `protobuf:"varint,4,opt,name=min_importance,json=minImportance,proto3,oneof" json:"min_importance,omitempty"`
	MemoryTypes     []MemoryType           `protobuf:"varint,5,rep,packed,name=memory_types,json=memoryTypes,proto3,enum=mnemosyne.v1.MemoryType" json:"memory_types,omitempty"`
	Tags            []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	IncludeArchived bool                   `protobuf:"varint,7,opt,name=include_archived,json=includeArchived,proto3" json:"include_archived,omitempty"`
	// Score weighting (must sum to 1.0)
	SemanticWeight *float32 `protobuf:"fixed32,8,opt,name=semantic_weight,json=semanticWeight,proto3,oneof" json:"semantic_weight,omitempty"` // Default: 0.7
	FtsWeight      *float32 `protobuf:"fixed32,9,opt,name=fts_weight,json=ftsWeight,proto3,oneof" json:"fts_weight,omitempty"`                // Default: 0.2
	GraphWeight    *float32 `protobuf:"fixed32,10,opt,name=graph_weight,json=graphWeight,proto3,oneof" json:"graph_weight,omitempty"`         // Default: 0.1
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecallRequest) Reset() {
	*x = RecallRequest{}
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallRequest) ProtoMessage() {}

func (x *RecallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallRequest.ProtoReflect.Descriptor instead.
func (*RecallRequest) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_memory_proto_rawDescGZIP(), []int{11}
}

func (x *RecallRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RecallRequest) GetNamespace() *Namespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *RecallRequest) GetMaxResults() uint32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

func (x *RecallRequest) GetMinImportance() uint32 {
	if x != nil && x.MinImportance != nil {
		return *x.MinImportance
	}
	return 0
}

func (x *RecallRequest) GetMemoryTypes() []MemoryType {
	if x != nil {
		return x.MemoryTypes
	}
	return nil
}

func (x *RecallRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *RecallRequest) GetIncludeArchived() bool {
	if x != nil {
		return x.IncludeArchived
	}
	return false
}

func (x *RecallRequest) GetSemanticWeight() float32 {
	if x != nil && x.SemanticWeight != nil {
		return *x.SemanticWeight
	}
	return 0
}

func (x *RecallRequest) GetFtsWeight() float32 {
	if x != nil && x.FtsWeight != nil {
		return *x.FtsWeight
	}
	return 0
}

func (x *RecallRequest) GetGraphWeight() float32 {
	if x != nil && x.GraphWeight != nil {
		return *x.GraphWeight
	}
	return 0
}

type RecallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`                                    // Echo back for confirmation
	TotalMatches  uint32                 `protobuf:"varint,3,opt,name=total_matches,json=totalMatches,proto3" json:"total_matches,omitempty"` // Before max_results limit
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecallResponse) Reset() {
	*x = RecallResponse{}
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecallResponse) ProtoMessage() {}

func (x *RecallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecallResponse.ProtoReflect.Descriptor instead.
func (*RecallResponse) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_memory_proto_rawDescGZIP(), []int{12}
}

func (x *RecallResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *RecallResponse) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RecallResponse) GetTotalMatches() uint32 {
	if x != nil {
		return x.TotalMatches
	}
	return 0
}

type SemanticSearchRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Embedding       []float32              `protobuf:"fixed32,1,rep,packed,name=embedding,proto3" json:"embedding,omitempty"` // 768d or 1536d vector
	Namespace       *Namespace             `protobuf:"bytes,2,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	MaxResults      uint32                 `protobuf:"varint,3,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"` // Default: 10
	MinImportance   *uint32                `protobuf:"varint,4,opt,name=min_importance,json=minImportance,proto3,oneof" json:"min_importance,omitempty"`
	IncludeArchived bool                   `protobuf:"varint,5,opt,name=include_archived,json=includeArchived,proto3" json:"include_archived,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SemanticSearchRequest) Reset() {
	*x = SemanticSearchRequest{}
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticSearchRequest) ProtoMessage() {}

func (x *SemanticSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticSearchRequest.ProtoReflect.Descriptor instead.
func (*SemanticSearchRequest) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_memory_proto_rawDescGZIP(), []int{13}
}

func (x *SemanticSearchRequest) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *SemanticSearchRequest) GetNamespace() *Namespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *SemanticSearchRequest) GetMaxResults() uint32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

func (x *SemanticSearchRequest) GetMinImportance() uint32 {
	if x != nil && x.MinImportance != nil {
		return *x.MinImportance
	}
	return 0
}

func (x *SemanticSearchRequest) GetIncludeArchived() bool {
	if x != nil {
		return x.IncludeArchived
	}
	return false
}

type SemanticSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemanticSearchResponse) Reset() {
	*x = SemanticSearchResponse{}
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemanticSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemanticSearchResponse) ProtoMessage() {}

func (x *SemanticSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemanticSearchResponse.ProtoReflect.Descriptor instead.
func (*SemanticSearchResponse) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_memory_proto_rawDescGZIP(), []int{14}
}

func (x *SemanticSearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type GraphTraverseRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SeedIds         []string               `protobuf:"bytes,1,rep,name=seed_ids,json=seedIds,proto3" json:"seed_ids,omitempty"`                                          // Starting memory IDs
	MaxHops         uint32                 `protobuf:"varint,2,opt,name=max_hops,json=maxHops,proto3" json:"max_hops,omitempty"`                                         // Default: 2, max: 5
	LinkTypes       []LinkType             `protobuf:"varint,3,rep,packed,name=link_types,json=linkTypes,proto3,enum=mnemosyne.v1.LinkType" json:"link_types,omitempty"` // Filter by link types (empty = all)
	MinLinkStrength *float32               `protobuf:"fixed32,4,opt,name=min_link_strength,json=minLinkStrength,proto3,oneof" json:"min_link_strength,omitempty"`        // Minimum link strength
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GraphTraverseRequest) Reset() {
	*x = GraphTraverseRequest{}
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphTraverseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphTraverseRequest) ProtoMessage() {}

func (x *GraphTraverseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphTraverseRequest.ProtoReflect.Descriptor instead.
func (*GraphTraverseRequest) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_memory_proto_rawDescGZIP(), []int{15}
}

func (x *GraphTraverseRequest) GetSeedIds() []string {
	if x != nil {
		return x.SeedIds
	}
	return nil
}

func (x *GraphTraverseRequest) GetMaxHops() uint32 {
	if x != nil {
		return x.MaxHops
	}
	return 0
}

func (x *GraphTraverseRequest) GetLinkTypes() []LinkType {
	if x != nil {
		return x.LinkTypes
	}
	return nil
}

func (x *GraphTraverseRequest) GetMinLinkStrength() float32 {
	if x != nil && x.MinLinkStrength != nil {
		return *x.MinLinkStrength
	}
	return 0
}

type GraphTraverseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memories      []*MemoryNote          `protobuf:"bytes,1,rep,name=memories,proto3" json:"memories,omitempty"`
	Edges         []*GraphEdge           `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"` // Edges in the subgraph
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphTraverseResponse) Reset() {
	*x = GraphTraverseResponse{}
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphTraverseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphTraverseResponse) ProtoMessage() {}

func (x *GraphTraverseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphTraverseResponse.ProtoReflect.Descriptor instead.
func (*GraphTraverseResponse) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_memory_proto_rawDescGZIP(), []int{16}
}

func (x *GraphTraverseResponse) GetMemories() []*MemoryNote {
	if x != nil {
		return x.Memories
	}
	return nil
}

func (x *GraphTraverseResponse) GetEdges() []*GraphEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

type GraphEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	TargetId      string                 `protobuf:"bytes,2,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	LinkType      LinkType               `protobuf:"varint,3,opt,name=link_type,json=linkType,proto3,enum=mnemosyne.v1.LinkType" json:"link_type,omitempty"`
	Strength      float32                `protobuf:"fixed32,4,opt,name=strength,proto3" json:"strength,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphEdge) Reset() {
	*x = GraphEdge{}
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphEdge) ProtoMessage() {}

func (x *GraphEdge) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphEdge.ProtoReflect.Descriptor instead.
func (*GraphEdge) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_memory_proto_rawDescGZIP(), []int{17}
}

func (x *GraphEdge) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *GraphEdge) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *GraphEdge) GetLinkType() LinkType {
	if x != nil {
		return x.LinkType
	}
	return LinkType_LINK_TYPE_UNSPECIFIED
}

func (x *GraphEdge) GetStrength() float32 {
	if x != nil {
		return x.Strength
	}
	return 0
}

type GetContextRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MemoryIds      []string               `protobuf:"bytes,1,rep,name=memory_ids,json=memoryIds,proto3" json:"memory_ids,omitempty"`
	IncludeLinks   bool                   `protobuf:"varint,2,opt,name=include_links,json=includeLinks,proto3" json:"include_links,omitempty"`         // Default: true
	MaxLinkedDepth uint32                 `protobuf:"varint,3,opt,name=max_linked_depth,json=maxLinkedDepth,proto3" json:"max_linked_depth,omitempty"` // Default: 1 (immediate neighbors)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetContextRequest) Reset() {
	*x = GetContextRequest{}
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContextRequest) ProtoMessage() {}

func (x *GetContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContextRequest.ProtoReflect.Descriptor instead.
func (*GetContextRequest) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_memory_proto_rawDescGZIP(), []int{18}
}

func (x *GetContextRequest) GetMemoryIds() []string {
	if x != nil {
		return x.MemoryIds
	}
	return nil
}

func (x *GetContextRequest) GetIncludeLinks() bool {
	if x != nil {
		return x.IncludeLinks
	}
	return false
}

func (x *GetContextRequest) GetMaxLinkedDepth() uint32 {
	if x != nil {
		return x.MaxLinkedDepth
	}
	return 0
}

type GetContextResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Memories       []*MemoryNote          `protobuf:"bytes,1,rep,name=memories,proto3" json:"memories,omitempty"`                                   // Requested memories
	LinkedMemories []*MemoryNote          `protobuf:"bytes,2,rep,name=linked_memories,json=linkedMemories,proto3" json:"linked_memories,omitempty"` // Linked memories (if include_links=true)
	Edges          []*GraphEdge           `protobuf:"bytes,3,rep,name=edges,proto3" json:"edges,omitempty"`                                         // Edges between all memories
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetContextResponse) Reset() {
	*x = GetContextResponse{}
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContextResponse) ProtoMessage() {}

func (x *GetContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_memory_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContextResponse.ProtoReflect.Descriptor instead.
func (*GetContextResponse) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_memory_proto_rawDescGZIP(), []int{19}
}

func (x *GetContextResponse) GetMemories() []*MemoryNote {
	if x != nil {
		return x.Memories
	}
	return nil
}

func (x *GetContextResponse) GetLinkedMemories() []*MemoryNote {
	if x != nil {
		return x.LinkedMemories
	}
	return nil
}

func (x *GetContextResponse) GetEdges() []*GraphEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

var File_mnemosyne_v1_memory_proto protoreflect.FileDescriptor

const file_mnemosyne_v1_memory_proto_rawDesc = "" +
	"\n" +
	"\x19mnemosyne/v1/memory.proto\x12\fmnemosyne.v1\x1a\x18mnemosyne/v1/types.proto\"\xd8\x02\n" +
	"\x12StoreMemoryRequest\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x125\n" +
	"\tnamespace\x18\x02 \x01(\v2\x17.mnemosyne.v1.NamespaceR\tnamespace\x12#\n" +
	"\n" +
	"importance\x18\x03 \x01(\rH\x00R\n" +
	"importance\x88\x01\x01\x12\x1d\n" +
	"\acontext\x18\x04 \x01(\tH\x01R\acontext\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12>\n" +
	"\vmemory_type\x18\x06 \x01(\x0e2\x18.mnemosyne.v1.MemoryTypeH\x02R\n" +
	"memoryType\x88\x01\x01\x12.\n" +
	"\x13skip_llm_enrichment\x18\a \x01(\bR\x11skipLlmEnrichmentB\r\n" +
	"\v_importanceB\n" +
	"\n" +
	"\b_contextB\x0e\n" +
	"\f_memory_type\"d\n" +
	"\x13StoreMemoryResponse\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\tR\bmemoryId\x120\n" +
	"\x06memory\x18\x02 \x01(\v2\x18.mnemosyne.v1.MemoryNoteR\x06memory\"\xb7\x01\n" +
	"\x13StoreMemoryProgress\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12\x18\n" +
	"\apercent\x18\x02 \x01(\rR\apercent\x12 \n" +
	"\tmemory_id\x18\x03 \x01(\tH\x00R\bmemoryId\x88\x01\x01\x125\n" +
	"\x06memory\x18\x04 \x01(\v2\x18.mnemosyne.v1.MemoryNoteH\x01R\x06memory\x88\x01\x01B\f\n" +
	"\n" +
	"_memory_idB\t\n" +
	"\a_memory\"/\n" +
	"\x10GetMemoryRequest\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\tR\bmemoryId\"E\n" +
	"\x11GetMemoryResponse\x120\n" +
	"\x06memory\x18\x01 \x01(\v2\x18.mnemosyne.v1.MemoryNoteR\x06memory\"\xfe\x01\n" +
	"\x13UpdateMemoryRequest\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\tR\bmemoryId\x12\x1d\n" +
	"\acontent\x18\x02 \x01(\tH\x00R\acontent\x88\x01\x01\x12#\n" +
	"\n" +
	"importance\x18\x03 \x01(\rH\x01R\n" +
	"importance\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x19\n" +
	"\badd_tags\x18\x05 \x03(\tR\aaddTags\x12\x1f\n" +
	"\vremove_tags\x18\x06 \x03(\tR\n" +
	"removeTags\x12\x1b\n" +
	"\tre_enrich\x18\a \x01(\bR\breEnrichB\n" +
	"\n" +
	"\b_contentB\r\n" +
	"\v_importance\"H\n" +
	"\x14UpdateMemoryResponse\x120\n" +
	"\x06memory\x18\x01 \x01(\v2\x18.mnemosyne.v1.MemoryNoteR\x06memory\"2\n" +
	"\x13DeleteMemoryRequest\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\tR\bmemoryId\"0\n" +
	"\x14DeleteMemoryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x8e\x03\n" +
	"\x13ListMemoriesRequest\x12:\n" +
	"\tnamespace\x18\x01 \x01(\v2\x17.mnemosyne.v1.NamespaceH\x00R\tnamespace\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\rR\x05limit\x12\x1b\n" +
	"\x06offset\x18\x03 \x01(\rH\x01R\x06offset\x88\x01\x01\x12;\n" +
	"\fmemory_types\x18\x04 \x03(\x0e2\x18.mnemosyne.v1.MemoryTypeR\vmemoryTypes\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12*\n" +
	"\x0emin_importance\x18\x06 \x01(\rH\x02R\rminImportance\x88\x01\x01\x12)\n" +
	"\x10include_archived\x18\a \x01(\bR\x0fincludeArchived\x12\x17\n" +
	"\asort_by\x18\b \x01(\tR\x06sortBy\x12\x1b\n" +
	"\tsort_desc\x18\t \x01(\bR\bsortDescB\f\n" +
	"\n" +
	"_namespaceB\t\n" +
	"\a_offsetB\x11\n" +
	"\x0f_min_importance\"\x88\x01\n" +
	"\x14ListMemoriesResponse\x124\n" +
	"\bmemories\x18\x01 \x03(\v2\x18.mnemosyne.v1.MemoryNoteR\bmemories\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\rR\n" +
	"totalCount\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"\xf9\x03\n" +
	"\rRecallRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12:\n" +
	"\tnamespace\x18\x02 \x01(\v2\x17.mnemosyne.v1.NamespaceH\x00R\tnamespace\x88\x01\x01\x12\x1f\n" +
	"\vmax_results\x18\x03 \x01(\rR\n" +
	"maxResults\x12*\n" +
	"\x0emin_importance\x18\x04 \x01(\rH\x01R\rminImportance\x88\x01\x01\x12;\n" +
	"\fmemory_types\x18\x05 \x03(\x0e2\x18.mnemosyne.v1.MemoryTypeR\vmemoryTypes\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12)\n" +
	"\x10include_archived\x18\a \x01(\bR\x0fincludeArchived\x12,\n" +
	"\x0fsemantic_weight\x18\b \x01(\x02H\x02R\x0esemanticWeight\x88\x01\x01\x12\"\n" +
	"\n" +
	"fts_weight\x18\t \x01(\x02H\x03R\tftsWeight\x88\x01\x01\x12&\n" +
	"\fgraph_weight\x18\n" +
	" \x01(\x02H\x04R\vgraphWeight\x88\x01\x01B\f\n" +
	"\n" +
	"_namespaceB\x11\n" +
	"\x0f_min_importanceB\x12\n" +
	"\x10_semantic_weightB\r\n" +
	"\v_fts_weightB\x0f\n" +
	"\r_graph_weight\"\x81\x01\n" +
	"\x0eRecallResponse\x124\n" +
	"\aresults\x18\x01 \x03(\v2\x1a.mnemosyne.v1.SearchResultR\aresults\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12#\n" +
	"\rtotal_matches\x18\x03 \x01(\rR\ftotalMatches\"\x8a\x02\n" +
	"\x15SemanticSearchRequest\x12\x1c\n" +
	"\tembedding\x18\x01 \x03(\x02R\tembedding\x12:\n" +
	"\tnamespace\x18\x02 \x01(\v2\x17.mnemosyne.v1.NamespaceH\x00R\tnamespace\x88\x01\x01\x12\x1f\n" +
	"\vmax_results\x18\x03 \x01(\rR\n" +
	"maxResults\x12*\n" +
	"\x0emin_importance\x18\x04 \x01(\rH\x01R\rminImportance\x88\x01\x01\x12)\n" +
	"\x10include_archived\x18\x05 \x01(\bR\x0fincludeArchivedB\f\n" +
	"\n" +
	"_namespaceB\x11\n" +
	"\x0f_min_importance\"N\n" +
	"\x16SemanticSearchResponse\x124\n" +
	"\aresults\x18\x01 \x03(\v2\x1a.mnemosyne.v1.SearchResultR\aresults\"\xca\x01\n" +
	"\x14GraphTraverseRequest\x12\x19\n" +
	"\bseed_ids\x18\x01 \x03(\tR\aseedIds\x12\x19\n" +
	"\bmax_hops\x18\x02 \x01(\rR\amaxHops\x125\n" +
	"\n" +
	"link_types\x18\x03 \x03(\x0e2\x16.mnemosyne.v1.LinkTypeR\tlinkTypes\x12/\n" +
	"\x11min_link_strength\x18\x04 \x01(\x02H\x00R\x0fminLinkStrength\x88\x01\x01B\x14\n" +
	"\x12_min_link_strength\"|\n" +
	"\x15GraphTraverseResponse\x124\n" +
	"\bmemories\x18\x01 \x03(\v2\x18.mnemosyne.v1.MemoryNoteR\bmemories\x12-\n" +
	"\x05edges\x18\x02 \x03(\v2\x17.mnemosyne.v1.GraphEdgeR\x05edges\"\x96\x01\n" +
	"\tGraphEdge\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x123\n" +
	"\tlink_type\x18\x03 \x01(\x0e2\x16.mnemosyne.v1.LinkTypeR\blinkType\x12\x1a\n" +
	"\bstrength\x18\x04 \x01(\x02R\bstrength\"\x81\x01\n" +
	"\x11GetContextRequest\x12\x1d\n" +
	"\n" +
	"memory_ids\x18\x01 \x03(\tR\tmemoryIds\x12#\n" +
	"\rinclude_links\x18\x02 \x01(\bR\fincludeLinks\x12(\n" +
	"\x10max_linked_depth\x18\x03 \x01(\rR\x0emaxLinkedDepth\"\xbc\x01\n" +
	"\x12GetContextResponse\x124\n" +
	"\bmemories\x18\x01 \x03(\v2\x18.mnemosyne.v1.MemoryNoteR\bmemories\x12A\n" +
	"\x0flinked_memories\x18\x02 \x03(\v2\x18.mnemosyne.v1.MemoryNoteR\x0elinkedMemories\x12-\n" +
	"\x05edges\x18\x03 \x03(\v2\x17.mnemosyne.v1.GraphEdgeR\x05edges2\xff\a\n" +
	"\rMemoryService\x12R\n" +
	"\vStoreMemory\x12 .mnemosyne.v1.StoreMemoryRequest\x1a!.mnemosyne.v1.StoreMemoryResponse\x12L\n" +
	"\tGetMemory\x12\x1e.mnemosyne.v1.GetMemoryRequest\x1a\x1f.mnemosyne.v1.GetMemoryResponse\x12U\n" +
	"\fUpdateMemory\x12!.mnemosyne.v1.UpdateMemoryRequest\x1a\".mnemosyne.v1.UpdateMemoryResponse\x12U\n" +
	"\fDeleteMemory\x12!.mnemosyne.v1.DeleteMemoryRequest\x1a\".mnemosyne.v1.DeleteMemoryResponse\x12U\n" +
	"\fListMemories\x12!.mnemosyne.v1.ListMemoriesRequest\x1a\".mnemosyne.v1.ListMemoriesResponse\x12C\n" +
	"\x06Recall\x12\x1b.mnemosyne.v1.RecallRequest\x1a\x1c.mnemosyne.v1.RecallResponse\x12[\n" +
	"\x0eSemanticSearch\x12#.mnemosyne.v1.SemanticSearchRequest\x1a$.mnemosyne.v1.SemanticSearchResponse\x12X\n" +
	"\rGraphTraverse\x12\".mnemosyne.v1.GraphTraverseRequest\x1a#.mnemosyne.v1.GraphTraverseResponse\x12O\n" +
	"\n" +
	"GetContext\x12\x1f.mnemosyne.v1.GetContextRequest\x1a .mnemosyne.v1.GetContextResponse\x12I\n" +
	"\fRecallStream\x12\x1b.mnemosyne.v1.RecallRequest\x1a\x1a.mnemosyne.v1.SearchResult0\x01\x12S\n" +
	"\x12ListMemoriesStream\x12!.mnemosyne.v1.ListMemoriesRequest\x1a\x18.mnemosyne.v1.MemoryNote0\x01\x12Z\n" +
	"\x11StoreMemoryStream\x12 .mnemosyne.v1.StoreMemoryRequest\x1a!.mnemosyne.v1.StoreMemoryProgress0\x01B6Z4github.com/rand/pedantic-raven/internal/mnemosyne/pbb\x06proto3"

var (
	file_mnemosyne_v1_memory_proto_rawDescOnce sync.Once
	file_mnemosyne_v1_memory_proto_rawDescData []byte
)

func file_mnemosyne_v1_memory_proto_rawDescGZIP() []byte {
	file_mnemosyne_v1_memory_proto_rawDescOnce.Do(func() {
		file_mnemosyne_v1_memory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mnemosyne_v1_memory_proto_rawDesc), len(file_mnemosyne_v1_memory_proto_rawDesc)))
	})
	return file_mnemosyne_v1_memory_proto_rawDescData
}

var file_mnemosyne_v1_memory_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_mnemosyne_v1_memory_proto_goTypes = []any{
	(*StoreMemoryRequest)(nil),     // 0: mnemosyne.v1.StoreMemoryRequest
	(*StoreMemoryResponse)(nil),    // 1: mnemosyne.v1.StoreMemoryResponse
	(*StoreMemoryProgress)(nil),    // 2: mnemosyne.v1.StoreMemoryProgress
	(*GetMemoryRequest)(nil),       // 3: mnemosyne.v1.GetMemoryRequest
	(*GetMemoryResponse)(nil),      // 4: mnemosyne.v1.GetMemoryResponse
	(*UpdateMemoryRequest)(nil),    // 5: mnemosyne.v1.UpdateMemoryRequest
	(*UpdateMemoryResponse)(nil),   // 6: mnemosyne.v1.UpdateMemoryResponse
	(*DeleteMemoryRequest)(nil),    // 7: mnemosyne.v1.DeleteMemoryRequest
	(*DeleteMemoryResponse)(nil),   // 8: mnemosyne.v1.DeleteMemoryResponse
	(*ListMemoriesRequest)(nil),    // 9: mnemosyne.v1.ListMemoriesRequest
	(*ListMemoriesResponse)(nil),   // 10: mnemosyne.v1.ListMemoriesResponse
	(*RecallRequest)(nil),          // 11: mnemosyne.v1.RecallRequest
	(*RecallResponse)(nil),         // 12: mnemosyne.v1.RecallResponse
	(*SemanticSearchRequest)(nil),  // 13: mnemosyne.v1.SemanticSearchRequest
	(*SemanticSearchResponse)(nil), // 14: mnemosyne.v1.SemanticSearchResponse
	(*GraphTraverseRequest)(nil),   // 15: mnemosyne.v1.GraphTraverseRequest
	(*GraphTraverseResponse)(nil),  // 16: mnemosyne.v1.GraphTraverseResponse
	(*GraphEdge)(nil),              // 17: mnemosyne.v1.GraphEdge
	(*GetContextRequest)(nil),      // 18: mnemosyne.v1.GetContextRequest
	(*GetContextResponse)(nil),     // 19: mnemosyne.v1.GetContextResponse
	(*Namespace)(nil),              // 20: mnemosyne.v1.Namespace
	(MemoryType)(0),                // 21: mnemosyne.v1.MemoryType
	(*MemoryNote)(nil),             // 22: mnemosyne.v1.MemoryNote
	(*SearchResult)(nil),           // 23: mnemosyne.v1.SearchResult
	(LinkType)(0),                  // 24: mnemosyne.v1.LinkType
}
var file_mnemosyne_v1_memory_proto_depIdxs = []int32{
	20, // 0: mnemosyne.v1.StoreMemoryRequest.namespace:type_name -> mnemosyne.v1.Namespace
	21, // 1: mnemosyne.v1.StoreMemoryRequest.memory_type:type_name -> mnemosyne.v1.MemoryType
	22, // 2: mnemosyne.v1.StoreMemoryResponse.memory:type_name -> mnemosyne.v1.MemoryNote
	22, // 3: mnemosyne.v1.StoreMemoryProgress.memory:type_name -> mnemosyne.v1.MemoryNote
	22, // 4: mnemosyne.v1.GetMemoryResponse.memory:type_name -> mnemosyne.v1.MemoryNote
	22, // 5: mnemosyne.v1.UpdateMemoryResponse.memory:type_name -> mnemosyne.v1.MemoryNote
	20, // 6: mnemosyne.v1.ListMemoriesRequest.namespace:type_name -> mnemosyne.v1.Namespace
	21, // 7: mnemosyne.v1.ListMemoriesRequest.memory_types:type_name -> mnemosyne.v1.MemoryType
	22, // 8: mnemosyne.v1.ListMemoriesResponse.memories:type_name -> mnemosyne.v1.MemoryNote
	20, // 9: mnemosyne.v1.RecallRequest.namespace:type_name -> mnemosyne.v1.Namespace
	21, // 10: mnemosyne.v1.RecallRequest.memory_types:type_name -> mnemosyne.v1.MemoryType
	23, // 11: mnemosyne.v1.RecallResponse.results:type_name -> mnemosyne.v1.SearchResult
	20, // 12: mnemosyne.v1.SemanticSearchRequest.namespace:type_name -> mnemosyne.v1.Namespace
	23, // 13: mnemosyne.v1.SemanticSearchResponse.results:type_name -> mnemosyne.v1.SearchResult
	24, // 14: mnemosyne.v1.GraphTraverseRequest.link_types:type_name -> mnemosyne.v1.LinkType
	22, // 15: mnemosyne.v1.GraphTraverseResponse.memories:type_name -> mnemosyne.v1.MemoryNote
	17, // 16: mnemosyne.v1.GraphTraverseResponse.edges:type_name -> mnemosyne.v1.GraphEdge
	24, // 17: mnemosyne.v1.GraphEdge.link_type:type_name -> mnemosyne.v1.LinkType
	22, // 18: mnemosyne.v1.GetContextResponse.memories:type_name -> mnemosyne.v1.MemoryNote
	22, // 19: mnemosyne.v1.GetContextResponse.linked_memories:type_name -> mnemosyne.v1.MemoryNote
	17, // 20: mnemosyne.v1.GetContextResponse.edges:type_name -> mnemosyne.v1.GraphEdge
	0,  // 21: mnemosyne.v1.MemoryService.StoreMemory:input_type -> mnemosyne.v1.StoreMemoryRequest
	3,  // 22: mnemosyne.v1.MemoryService.GetMemory:input_type -> mnemosyne.v1.GetMemoryRequest
	5,  // 23: mnemosyne.v1.MemoryService.UpdateMemory:input_type -> mnemosyne.v1.UpdateMemoryRequest
	7,  // 24: mnemosyne.v1.MemoryService.DeleteMemory:input_type -> mnemosyne.v1.DeleteMemoryRequest
	9,  // 25: mnemosyne.v1.MemoryService.ListMemories:input_type -> mnemosyne.v1.ListMemoriesRequest
	11, // 26: mnemosyne.v1.MemoryService.Recall:input_type -> mnemosyne.v1.RecallRequest
	13, // 27: mnemosyne.v1.MemoryService.SemanticSearch:input_type -> mnemosyne.v1.SemanticSearchRequest
	15, // 28: mnemosyne.v1.MemoryService.GraphTraverse:input_type -> mnemosyne.v1.GraphTraverseRequest
	18, // 29: mnemosyne.v1.MemoryService.GetContext:input_type -> mnemosyne.v1.GetContextRequest
	11, // 30: mnemosyne.v1.MemoryService.RecallStream:input_type -> mnemosyne.v1.RecallRequest
	9,  // 31: mnemosyne.v1.MemoryService.ListMemoriesStream:input_type -> mnemosyne.v1.ListMemoriesRequest
	0,  // 32: mnemosyne.v1.MemoryService.StoreMemoryStream:input_type -> mnemosyne.v1.StoreMemoryRequest
	1,  // 33: mnemosyne.v1.MemoryService.StoreMemory:output_type -> mnemosyne.v1.StoreMemoryResponse
	4,  // 34: mnemosyne.v1.MemoryService.GetMemory:output_type -> mnemosyne.v1.GetMemoryResponse
	6,  // 35: mnemosyne.v1.MemoryService.UpdateMemory:output_type -> mnemosyne.v1.UpdateMemoryResponse
	8,  // 36: mnemosyne.v1.MemoryService.DeleteMemory:output_type -> mnemosyne.v1.DeleteMemoryResponse
	10, // 37: mnemosyne.v1.MemoryService.ListMemories:output_type -> mnemosyne.v1.ListMemoriesResponse
	12, // 38: mnemosyne.v1.MemoryService.Recall:output_type -> mnemosyne.v1.RecallResponse
	14, // 39: mnemosyne.v1.MemoryService.SemanticSearch:output_type -> mnemosyne.v1.SemanticSearchResponse
	16, // 40: mnemosyne.v1.MemoryService.GraphTraverse:output_type -> mnemosyne.v1.GraphTraverseResponse
	19, // 41: mnemosyne.v1.MemoryService.GetContext:output_type -> mnemosyne.v1.GetContextResponse
	23, // 42: mnemosyne.v1.MemoryService.RecallStream:output_type -> mnemosyne.v1.SearchResult
	22, // 43: mnemosyne.v1.MemoryService.ListMemoriesStream:output_type -> mnemosyne.v1.MemoryNote
	2,  // 44: mnemosyne.v1.MemoryService.StoreMemoryStream:output_type -> mnemosyne.v1.StoreMemoryProgress
	33, // [33:45] is the sub-list for method output_type
	21, // [21:33] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_mnemosyne_v1_memory_proto_init() }
func file_mnemosyne_v1_memory_proto_init() {
	if File_mnemosyne_v1_memory_proto != nil {
		return
	}
	file_mnemosyne_v1_types_proto_init()
	file_mnemosyne_v1_memory_proto_msgTypes[0].OneofWrappers = []any{}
	file_mnemosyne_v1_memory_proto_msgTypes[2].OneofWrappers = []any{}
	file_mnemosyne_v1_memory_proto_msgTypes[5].OneofWrappers = []any{}
	file_mnemosyne_v1_memory_proto_msgTypes[9].OneofWrappers = []any{}
	file_mnemosyne_v1_memory_proto_msgTypes[11].OneofWrappers = []any{}
	file_mnemosyne_v1_memory_proto_msgTypes[13].OneofWrappers = []any{}
	file_mnemosyne_v1_memory_proto_msgTypes[15].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mnemosyne_v1_memory_proto_rawDesc), len(file_mnemosyne_v1_memory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mnemosyne_v1_memory_proto_goTypes,
		DependencyIndexes: file_mnemosyne_v1_memory_proto_depIdxs,
		MessageInfos:      file_mnemosyne_v1_memory_proto_msgTypes,
	}.Build()
	File_mnemosyne_v1_memory_proto = out.File
	file_mnemosyne_v1_memory_proto_goTypes = nil
	file_mnemosyne_v1_memory_proto_depIdxs = nil
}
