// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: mnemosyne/v1/memory.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MemoryService_StoreMemory_FullMethodName        = "/mnemosyne.v1.MemoryService/StoreMemory"
	MemoryService_GetMemory_FullMethodName          = "/mnemosyne.v1.MemoryService/GetMemory"
	MemoryService_UpdateMemory_FullMethodName       = "/mnemosyne.v1.MemoryService/UpdateMemory"
	MemoryService_DeleteMemory_FullMethodName       = "/mnemosyne.v1.MemoryService/DeleteMemory"
	MemoryService_ListMemories_FullMethodName       = "/mnemosyne.v1.MemoryService/ListMemories"
	MemoryService_Recall_FullMethodName             = "/mnemosyne.v1.MemoryService/Recall"
	MemoryService_SemanticSearch_FullMethodName     = "/mnemosyne.v1.MemoryService/SemanticSearch"
	MemoryService_GraphTraverse_FullMethodName      = "/mnemosyne.v1.MemoryService/GraphTraverse"
	MemoryService_GetContext_FullMethodName         = "/mnemosyne.v1.MemoryService/GetContext"
	MemoryService_RecallStream_FullMethodName       = "/mnemosyne.v1.MemoryService/RecallStream"
	MemoryService_ListMemoriesStream_FullMethodName = "/mnemosyne.v1.MemoryService/ListMemoriesStream"
	MemoryService_StoreMemoryStream_FullMethodName  = "/mnemosyne.v1.MemoryService/StoreMemoryStream"
)

// MemoryServiceClient is the client API for MemoryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MemoryService provides CRUD operations and search for memory notes
type MemoryServiceClient interface {
	// Store a new memory note (with LLM enrichment if enabled)
	StoreMemory(ctx context.Context, in *StoreMemoryRequest, opts ...grpc.CallOption) (*StoreMemoryResponse, error)
	// Get a memory note by ID
	GetMemory(ctx context.Context, in *GetMemoryRequest, opts ...grpc.CallOption) (*GetMemoryResponse, error)
	// Update an existing memory note
	UpdateMemory(ctx context.Context, in *UpdateMemoryRequest, opts ...grpc.CallOption) (*UpdateMemoryResponse, error)
	// Delete a memory note
	DeleteMemory(ctx context.Context, in *DeleteMemoryRequest, opts ...grpc.CallOption) (*DeleteMemoryResponse, error)
	// List memories with filters
	ListMemories(ctx context.Context, in *ListMemoriesRequest, opts ...grpc.CallOption) (*ListMemoriesResponse, error)
	// Hybrid search (semantic + FTS + graph)
	Recall(ctx context.Context, in *RecallRequest, opts ...grpc.CallOption) (*RecallResponse, error)
	// Pure semantic search using embedding vector
	SemanticSearch(ctx context.Context, in *SemanticSearchRequest, opts ...grpc.CallOption) (*SemanticSearchResponse, error)
	// Traverse the memory graph from seed nodes
	GraphTraverse(ctx context.Context, in *GraphTraverseRequest, opts ...grpc.CallOption) (*GraphTraverseResponse, error)
	// Get context around specific memories (including linked memories)
	GetContext(ctx context.Context, in *GetContextRequest, opts ...grpc.CallOption) (*GetContextResponse, error)
	// Stream search results as they're found
	RecallStream(ctx context.Context, in *RecallRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SearchResult], error)
	// Stream memories in batches
	ListMemoriesStream(ctx context.Context, in *ListMemoriesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MemoryNote], error)
	// Store memory with progress updates (for slow LLM enrichment)
	StoreMemoryStream(ctx context.Context, in *StoreMemoryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StoreMemoryProgress], error)
}

type memoryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMemoryServiceClient(cc grpc.ClientConnInterface) MemoryServiceClient {
	return &memoryServiceClient{cc}
}

func (c *memoryServiceClient) StoreMemory(ctx context.Context, in *StoreMemoryRequest, opts ...grpc.CallOption) (*StoreMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreMemoryResponse)
	err := c.cc.Invoke(ctx, MemoryService_StoreMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) GetMemory(ctx context.Context, in *GetMemoryRequest, opts ...grpc.CallOption) (*GetMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMemoryResponse)
	err := c.cc.Invoke(ctx, MemoryService_GetMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) UpdateMemory(ctx context.Context, in *UpdateMemoryRequest, opts ...grpc.CallOption) (*UpdateMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMemoryResponse)
	err := c.cc.Invoke(ctx, MemoryService_UpdateMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) DeleteMemory(ctx context.Context, in *DeleteMemoryRequest, opts ...grpc.CallOption) (*DeleteMemoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMemoryResponse)
	err := c.cc.Invoke(ctx, MemoryService_DeleteMemory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) ListMemories(ctx context.Context, in *ListMemoriesRequest, opts ...grpc.CallOption) (*ListMemoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMemoriesResponse)
	err := c.cc.Invoke(ctx, MemoryService_ListMemories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) Recall(ctx context.Context, in *RecallRequest, opts ...grpc.CallOption) (*RecallResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecallResponse)
	err := c.cc.Invoke(ctx, MemoryService_Recall_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) SemanticSearch(ctx context.Context, in *SemanticSearchRequest, opts ...grpc.CallOption) (*SemanticSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SemanticSearchResponse)
	err := c.cc.Invoke(ctx, MemoryService_SemanticSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) GraphTraverse(ctx context.Context, in *GraphTraverseRequest, opts ...grpc.CallOption) (*GraphTraverseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GraphTraverseResponse)
	err := c.cc.Invoke(ctx, MemoryService_GraphTraverse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) GetContext(ctx context.Context, in *GetContextRequest, opts ...grpc.CallOption) (*GetContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContextResponse)
	err := c.cc.Invoke(ctx, MemoryService_GetContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memoryServiceClient) RecallStream(ctx context.Context, in *RecallRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SearchResult], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MemoryService_ServiceDesc.Streams[0], MemoryService_RecallStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RecallRequest, SearchResult]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MemoryService_RecallStreamClient = grpc.ServerStreamingClient[SearchResult]

func (c *memoryServiceClient) ListMemoriesStream(ctx context.Context, in *ListMemoriesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MemoryNote], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MemoryService_ServiceDesc.Streams[1], MemoryService_ListMemoriesStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ListMemoriesRequest, MemoryNote]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MemoryService_ListMemoriesStreamClient = grpc.ServerStreamingClient[MemoryNote]

func (c *memoryServiceClient) StoreMemoryStream(ctx context.Context, in *StoreMemoryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StoreMemoryProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MemoryService_ServiceDesc.Streams[2], MemoryService_StoreMemoryStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StoreMemoryRequest, StoreMemoryProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MemoryService_StoreMemoryStreamClient = grpc.ServerStreamingClient[StoreMemoryProgress]

// MemoryServiceServer is the server API for MemoryService service.
// All implementations must embed UnimplementedMemoryServiceServer
// for forward compatibility.
//
// MemoryService provides CRUD operations and search for memory notes
type MemoryServiceServer interface {
	// Store a new memory note (with LLM enrichment if enabled)
	StoreMemory(context.Context, *StoreMemoryRequest) (*StoreMemoryResponse, error)
	// Get a memory note by ID
	GetMemory(context.Context, *GetMemoryRequest) (*GetMemoryResponse, error)
	// Update an existing memory note
	UpdateMemory(context.Context, *UpdateMemoryRequest) (*UpdateMemoryResponse, error)
	// Delete a memory note
	DeleteMemory(context.Context, *DeleteMemoryRequest) (*DeleteMemoryResponse, error)
	// List memories with filters
	ListMemories(context.Context, *ListMemoriesRequest) (*ListMemoriesResponse, error)
	// Hybrid search (semantic + FTS + graph)
	Recall(context.Context, *RecallRequest) (*RecallResponse, error)
	// Pure semantic search using embedding vector
	SemanticSearch(context.Context, *SemanticSearchRequest) (*SemanticSearchResponse, error)
	// Traverse the memory graph from seed nodes
	GraphTraverse(context.Context, *GraphTraverseRequest) (*GraphTraverseResponse, error)
	// Get context around specific memories (including linked memories)
	GetContext(context.Context, *GetContextRequest) (*GetContextResponse, error)
	// Stream search results as they're found
	RecallStream(*RecallRequest, grpc.ServerStreamingServer[SearchResult]) error
	// Stream memories in batches
	ListMemoriesStream(*ListMemoriesRequest, grpc.ServerStreamingServer[MemoryNote]) error
	// Store memory with progress updates (for slow LLM enrichment)
	StoreMemoryStream(*StoreMemoryRequest, grpc.ServerStreamingServer[StoreMemoryProgress]) error
	mustEmbedUnimplementedMemoryServiceServer()
}

// UnimplementedMemoryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMemoryServiceServer struct{}

func (UnimplementedMemoryServiceServer) StoreMemory(context.Context, *StoreMemoryRequest) (*StoreMemoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreMemory not implemented")
}
func (UnimplementedMemoryServiceServer) GetMemory(context.Context, *GetMemoryRequest) (*GetMemoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMemory not implemented")
}
func (UnimplementedMemoryServiceServer) UpdateMemory(context.Context, *UpdateMemoryRequest) (*UpdateMemoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMemory not implemented")
}
func (UnimplementedMemoryServiceServer) DeleteMemory(context.Context, *DeleteMemoryRequest) (*DeleteMemoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMemory not implemented")
}
func (UnimplementedMemoryServiceServer) ListMemories(context.Context, *ListMemoriesRequest) (*ListMemoriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMemories not implemented")
}
func (UnimplementedMemoryServiceServer) Recall(context.Context, *RecallRequest) (*RecallResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Recall not implemented")
}
func (UnimplementedMemoryServiceServer) SemanticSearch(context.Context, *SemanticSearchRequest) (*SemanticSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SemanticSearch not implemented")
}
func (UnimplementedMemoryServiceServer) GraphTraverse(context.Context, *GraphTraverseRequest) (*GraphTraverseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GraphTraverse not implemented")
}
func (UnimplementedMemoryServiceServer) GetContext(context.Context, *GetContextRequest) (*GetContextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContext not implemented")
}
func (UnimplementedMemoryServiceServer) RecallStream(*RecallRequest, grpc.ServerStreamingServer[SearchResult]) error {
	return status.Errorf(codes.Unimplemented, "method RecallStream not implemented")
}
func (UnimplementedMemoryServiceServer) ListMemoriesStream(*ListMemoriesRequest, grpc.ServerStreamingServer[MemoryNote]) error {
	return status.Errorf(codes.Unimplemented, "method ListMemoriesStream not implemented")
}
func (UnimplementedMemoryServiceServer) StoreMemoryStream(*StoreMemoryRequest, grpc.ServerStreamingServer[StoreMemoryProgress]) error {
	return status.Errorf(codes.Unimplemented, "method StoreMemoryStream not implemented")
}
func (UnimplementedMemoryServiceServer) mustEmbedUnimplementedMemoryServiceServer() {}
func (UnimplementedMemoryServiceServer) testEmbeddedByValue()                       {}

// UnsafeMemoryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MemoryServiceServer will
// result in compilation errors.
type UnsafeMemoryServiceServer interface {
	mustEmbedUnimplementedMemoryServiceServer()
}

func RegisterMemoryServiceServer(s grpc.ServiceRegistrar, srv MemoryServiceServer) {
	// If the following call pancis, it indicates UnimplementedMemoryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MemoryService_ServiceDesc, srv)
}

func _MemoryService_StoreMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).StoreMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_StoreMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).StoreMemory(ctx, req.(*StoreMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_GetMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).GetMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_GetMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).GetMemory(ctx, req.(*GetMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_UpdateMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).UpdateMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_UpdateMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).UpdateMemory(ctx, req.(*UpdateMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_DeleteMemory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMemoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).DeleteMemory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_DeleteMemory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).DeleteMemory(ctx, req.(*DeleteMemoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_ListMemories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMemoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).ListMemories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_ListMemories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).ListMemories(ctx, req.(*ListMemoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_Recall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecallRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).Recall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_Recall_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).Recall(ctx, req.(*RecallRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_SemanticSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SemanticSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).SemanticSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_SemanticSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).SemanticSearch(ctx, req.(*SemanticSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_GraphTraverse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphTraverseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).GraphTraverse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_GraphTraverse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).GraphTraverse(ctx, req.(*GraphTraverseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_GetContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemoryServiceServer).GetContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemoryService_GetContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemoryServiceServer).GetContext(ctx, req.(*GetContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemoryService_RecallStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RecallRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MemoryServiceServer).RecallStream(m, &grpc.GenericServerStream[RecallRequest, SearchResult]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MemoryService_RecallStreamServer = grpc.ServerStreamingServer[SearchResult]

func _MemoryService_ListMemoriesStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListMemoriesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MemoryServiceServer).ListMemoriesStream(m, &grpc.GenericServerStream[ListMemoriesRequest, MemoryNote]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MemoryService_ListMemoriesStreamServer = grpc.ServerStreamingServer[MemoryNote]

func _MemoryService_StoreMemoryStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StoreMemoryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MemoryServiceServer).StoreMemoryStream(m, &grpc.GenericServerStream[StoreMemoryRequest, StoreMemoryProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MemoryService_StoreMemoryStreamServer = grpc.ServerStreamingServer[StoreMemoryProgress]

// MemoryService_ServiceDesc is the grpc.ServiceDesc for MemoryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MemoryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mnemosyne.v1.MemoryService",
	HandlerType: (*MemoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreMemory",
			Handler:    _MemoryService_StoreMemory_Handler,
		},
		{
			MethodName: "GetMemory",
			Handler:    _MemoryService_GetMemory_Handler,
		},
		{
			MethodName: "UpdateMemory",
			Handler:    _MemoryService_UpdateMemory_Handler,
		},
		{
			MethodName: "DeleteMemory",
			Handler:    _MemoryService_DeleteMemory_Handler,
		},
		{
			MethodName: "ListMemories",
			Handler:    _MemoryService_ListMemories_Handler,
		},
		{
			MethodName: "Recall",
			Handler:    _MemoryService_Recall_Handler,
		},
		{
			MethodName: "SemanticSearch",
			Handler:    _MemoryService_SemanticSearch_Handler,
		},
		{
			MethodName: "GraphTraverse",
			Handler:    _MemoryService_GraphTraverse_Handler,
		},
		{
			MethodName: "GetContext",
			Handler:    _MemoryService_GetContext_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RecallStream",
			Handler:       _MemoryService_RecallStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListMemoriesStream",
			Handler:       _MemoryService_ListMemoriesStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StoreMemoryStream",
			Handler:       _MemoryService_StoreMemoryStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "mnemosyne/v1/memory.proto",
}
