// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: mnemosyne/v1/types.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemoryType int32

const (
	MemoryType_MEMORY_TYPE_UNSPECIFIED           MemoryType = 0
	MemoryType_MEMORY_TYPE_ARCHITECTURE_DECISION MemoryType = 1
	MemoryType_MEMORY_TYPE_CODE_PATTERN          MemoryType = 2
	MemoryType_MEMORY_TYPE_BUG_FIX               MemoryType = 3
	MemoryType_MEMORY_TYPE_CONFIGURATION         MemoryType = 4
	MemoryType_MEMORY_TYPE_CONSTRAINT            MemoryType = 5
	MemoryType_MEMORY_TYPE_ENTITY                MemoryType = 6
	MemoryType_MEMORY_TYPE_INSIGHT               MemoryType = 7
	MemoryType_MEMORY_TYPE_REFERENCE             MemoryType = 8
	MemoryType_MEMORY_TYPE_PREFERENCE            MemoryType = 9
	MemoryType_MEMORY_TYPE_TASK                  MemoryType = 10
	MemoryType_MEMORY_TYPE_AGENT_EVENT           MemoryType = 11
	MemoryType_MEMORY_TYPE_CONSTITUTION          MemoryType = 12
	MemoryType_MEMORY_TYPE_FEATURE_SPEC          MemoryType = 13
	MemoryType_MEMORY_TYPE_IMPLEMENTATION_PLAN   MemoryType = 14
	MemoryType_MEMORY_TYPE_TASK_BREAKDOWN        MemoryType = 15
	MemoryType_MEMORY_TYPE_QUALITY_CHECKLIST     MemoryType = 16
	MemoryType_MEMORY_TYPE_CLARIFICATION         MemoryType = 17
)

// Enum value maps for MemoryType.
var (
	MemoryType_name = map[int32]string{
		0:  "MEMORY_TYPE_UNSPECIFIED",
		1:  "MEMORY_TYPE_ARCHITECTURE_DECISION",
		2:  "MEMORY_TYPE_CODE_PATTERN",
		3:  "MEMORY_TYPE_BUG_FIX",
		4:  "MEMORY_TYPE_CONFIGURATION",
		5:  "MEMORY_TYPE_CONSTRAINT",
		6:  "MEMORY_TYPE_ENTITY",
		7:  "MEMORY_TYPE_INSIGHT",
		8:  "MEMORY_TYPE_REFERENCE",
		9:  "MEMORY_TYPE_PREFERENCE",
		10: "MEMORY_TYPE_TASK",
		11: "MEMORY_TYPE_AGENT_EVENT",
		12: "MEMORY_TYPE_CONSTITUTION",
		13: "MEMORY_TYPE_FEATURE_SPEC",
		14: "MEMORY_TYPE_IMPLEMENTATION_PLAN",
		15: "MEMORY_TYPE_TASK_BREAKDOWN",
		16: "MEMORY_TYPE_QUALITY_CHECKLIST",
		17: "MEMORY_TYPE_CLARIFICATION",
	}
	MemoryType_value = map[string]int32{
		"MEMORY_TYPE_UNSPECIFIED":           0,
		"MEMORY_TYPE_ARCHITECTURE_DECISION": 1,
		"MEMORY_TYPE_CODE_PATTERN":          2,
		"MEMORY_TYPE_BUG_FIX":               3,
		"MEMORY_TYPE_CONFIGURATION":         4,
		"MEMORY_TYPE_CONSTRAINT":            5,
		"MEMORY_TYPE_ENTITY":                6,
		"MEMORY_TYPE_INSIGHT":               7,
		"MEMORY_TYPE_REFERENCE":             8,
		"MEMORY_TYPE_PREFERENCE":            9,
		"MEMORY_TYPE_TASK":                  10,
		"MEMORY_TYPE_AGENT_EVENT":           11,
		"MEMORY_TYPE_CONSTITUTION":          12,
		"MEMORY_TYPE_FEATURE_SPEC":          13,
		"MEMORY_TYPE_IMPLEMENTATION_PLAN":   14,
		"MEMORY_TYPE_TASK_BREAKDOWN":        15,
		"MEMORY_TYPE_QUALITY_CHECKLIST":     16,
		"MEMORY_TYPE_CLARIFICATION":         17,
	}
)

func (x MemoryType) Enum() *MemoryType {
	p := new(MemoryType)
	*p = x
	return p
}

func (x MemoryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MemoryType) Descriptor() protoreflect.EnumDescriptor {
	return file_mnemosyne_v1_types_proto_enumTypes[0].Descriptor()
}

func (MemoryType) Type() protoreflect.EnumType {
	return &file_mnemosyne_v1_types_proto_enumTypes[0]
}

func (x MemoryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MemoryType.Descriptor instead.
func (MemoryType) EnumDescriptor() ([]byte, []int) {
	return file_mnemosyne_v1_types_proto_rawDescGZIP(), []int{0}
}

type LinkType int32

const (
	LinkType_LINK_TYPE_UNSPECIFIED   LinkType = 0
	LinkType_LINK_TYPE_EXTENDS       LinkType = 1
	LinkType_LINK_TYPE_BUILDS_UPON   LinkType = 2
	LinkType_LINK_TYPE_CONTRADICTS   LinkType = 3
	LinkType_LINK_TYPE_IMPLEMENTS    LinkType = 4
	LinkType_LINK_TYPE_REFERENCES    LinkType = 5
	LinkType_LINK_TYPE_REFERENCED_BY LinkType = 6
	LinkType_LINK_TYPE_CLARIFIES     LinkType = 7
	LinkType_LINK_TYPE_SUPERSEDES    LinkType = 8
)

// Enum value maps for LinkType.
var (
	LinkType_name = map[int32]string{
		0: "LINK_TYPE_UNSPECIFIED",
		1: "LINK_TYPE_EXTENDS",
		2: "LINK_TYPE_BUILDS_UPON",
		3: "LINK_TYPE_CONTRADICTS",
		4: "LINK_TYPE_IMPLEMENTS",
		5: "LINK_TYPE_REFERENCES",
		6: "LINK_TYPE_REFERENCED_BY",
		7: "LINK_TYPE_CLARIFIES",
		8: "LINK_TYPE_SUPERSEDES",
	}
	LinkType_value = map[string]int32{
		"LINK_TYPE_UNSPECIFIED":   0,
		"LINK_TYPE_EXTENDS":       1,
		"LINK_TYPE_BUILDS_UPON":   2,
		"LINK_TYPE_CONTRADICTS":   3,
		"LINK_TYPE_IMPLEMENTS":    4,
		"LINK_TYPE_REFERENCES":    5,
		"LINK_TYPE_REFERENCED_BY": 6,
		"LINK_TYPE_CLARIFIES":     7,
		"LINK_TYPE_SUPERSEDES":    8,
	}
)

func (x LinkType) Enum() *LinkType {
	p := new(LinkType)
	*p = x
	return p
}

func (x LinkType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LinkType) Descriptor() protoreflect.EnumDescriptor {
	return file_mnemosyne_v1_types_proto_enumTypes[1].Descriptor()
}

func (LinkType) Type() protoreflect.EnumType {
	return &file_mnemosyne_v1_types_proto_enumTypes[1]
}

func (x LinkType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LinkType.Descriptor instead.
func (LinkType) EnumDescriptor() ([]byte, []int) {
	return file_mnemosyne_v1_types_proto_rawDescGZIP(), []int{1}
}

type ConsolidationDecision int32

const (
	ConsolidationDecision_CONSOLIDATION_DECISION_UNSPECIFIED ConsolidationDecision = 0
	ConsolidationDecision_CONSOLIDATION_DECISION_MERGE       ConsolidationDecision = 1
	ConsolidationDecision_CONSOLIDATION_DECISION_SUPERSEDE   ConsolidationDecision = 2
	ConsolidationDecision_CONSOLIDATION_DECISION_KEEP_BOTH   ConsolidationDecision = 3
)

// Enum value maps for ConsolidationDecision.
var (
	ConsolidationDecision_name = map[int32]string{
		0: "CONSOLIDATION_DECISION_UNSPECIFIED",
		1: "CONSOLIDATION_DECISION_MERGE",
		2: "CONSOLIDATION_DECISION_SUPERSEDE",
		3: "CONSOLIDATION_DECISION_KEEP_BOTH",
	}
	ConsolidationDecision_value = map[string]int32{
		"CONSOLIDATION_DECISION_UNSPECIFIED": 0,
		"CONSOLIDATION_DECISION_MERGE":       1,
		"CONSOLIDATION_DECISION_SUPERSEDE":   2,
		"CONSOLIDATION_DECISION_KEEP_BOTH":   3,
	}
)

func (x ConsolidationDecision) Enum() *ConsolidationDecision {
	p := new(ConsolidationDecision)
	*p = x
	return p
}

func (x ConsolidationDecision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConsolidationDecision) Descriptor() protoreflect.EnumDescriptor {
	return file_mnemosyne_v1_types_proto_enumTypes[2].Descriptor()
}

func (ConsolidationDecision) Type() protoreflect.EnumType {
	return &file_mnemosyne_v1_types_proto_enumTypes[2]
}

func (x ConsolidationDecision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConsolidationDecision.Descriptor instead.
func (ConsolidationDecision) EnumDescriptor() ([]byte, []int) {
	return file_mnemosyne_v1_types_proto_rawDescGZIP(), []int{2}
}

type AgentState int32

const (
	AgentState_AGENT_STATE_UNSPECIFIED AgentState = 0
	AgentState_AGENT_STATE_IDLE        AgentState = 1
	AgentState_AGENT_STATE_RUNNING     AgentState = 2
	AgentState_AGENT_STATE_BLOCKED     AgentState = 3
	AgentState_AGENT_STATE_FAILED      AgentState = 4
)

// Enum value maps for AgentState.
var (
	AgentState_name = map[int32]string{
		0: "AGENT_STATE_UNSPECIFIED",
		1: "AGENT_STATE_IDLE",
		2: "AGENT_STATE_RUNNING",
		3: "AGENT_STATE_BLOCKED",
		4: "AGENT_STATE_FAILED",
	}
	AgentState_value = map[string]int32{
		"AGENT_STATE_UNSPECIFIED": 0,
		"AGENT_STATE_IDLE":        1,
		"AGENT_STATE_RUNNING":     2,
		"AGENT_STATE_BLOCKED":     3,
		"AGENT_STATE_FAILED":      4,
	}
)

func (x AgentState) Enum() *AgentState {
	p := new(AgentState)
	*p = x
	return p
}

func (x AgentState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentState) Descriptor() protoreflect.EnumDescriptor {
	return file_mnemosyne_v1_types_proto_enumTypes[3].Descriptor()
}

func (AgentState) Type() protoreflect.EnumType {
	return &file_mnemosyne_v1_types_proto_enumTypes[3]
}

func (x AgentState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentState.Descriptor instead.
func (AgentState) EnumDescriptor() ([]byte, []int) {
	return file_mnemosyne_v1_types_proto_rawDescGZIP(), []int{3}
}

// Unique identifier for a memory note (UUIDv4)
type MemoryId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryId) Reset() {
	*x = MemoryId{}
	mi := &file_mnemosyne_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryId) ProtoMessage() {}

func (x *MemoryId) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryId.ProtoReflect.Descriptor instead.
func (*MemoryId) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *MemoryId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Namespace hierarchy for organizing memories
type Namespace struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Namespace:
	//
	//	*Namespace_Global
	//	*Namespace_Project
	//	*Namespace_Session
	Namespace     isNamespace_Namespace `protobuf_oneof:"namespace"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Namespace) Reset() {
	*x = Namespace{}
	mi := &file_mnemosyne_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Namespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namespace) ProtoMessage() {}

func (x *Namespace) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namespace.ProtoReflect.Descriptor instead.
func (*Namespace) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *Namespace) GetNamespace() isNamespace_Namespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *Namespace) GetGlobal() *GlobalNamespace {
	if x != nil {
		if x, ok := x.Namespace.(*Namespace_Global); ok {
			return x.Global
		}
	}
	return nil
}

func (x *Namespace) GetProject() *ProjectNamespace {
	if x != nil {
		if x, ok := x.Namespace.(*Namespace_Project); ok {
			return x.Project
		}
	}
	return nil
}

func (x *Namespace) GetSession() *SessionNamespace {
	if x != nil {
		if x, ok := x.Namespace.(*Namespace_Session); ok {
			return x.Session
		}
	}
	return nil
}

type isNamespace_Namespace interface {
	isNamespace_Namespace()
}

type Namespace_Global struct {
	Global *GlobalNamespace `protobuf:"bytes,1,opt,name=global,proto3,oneof"`
}

type Namespace_Project struct {
	Project *ProjectNamespace `protobuf:"bytes,2,opt,name=project,proto3,oneof"`
}

type Namespace_Session struct {
	Session *SessionNamespace `protobuf:"bytes,3,opt,name=session,proto3,oneof"`
}

func (*Namespace_Global) isNamespace_Namespace() {}

func (*Namespace_Project) isNamespace_Namespace() {}

func (*Namespace_Session) isNamespace_Namespace() {}

type GlobalNamespace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GlobalNamespace) Reset() {
	*x = GlobalNamespace{}
	mi := &file_mnemosyne_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GlobalNamespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalNamespace) ProtoMessage() {}

func (x *GlobalNamespace) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalNamespace.ProtoReflect.Descriptor instead.
func (*GlobalNamespace) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_types_proto_rawDescGZIP(), []int{2}
}

type ProjectNamespace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectNamespace) Reset() {
	*x = ProjectNamespace{}
	mi := &file_mnemosyne_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectNamespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectNamespace) ProtoMessage() {}

func (x *ProjectNamespace) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectNamespace.ProtoReflect.Descriptor instead.
func (*ProjectNamespace) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectNamespace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SessionNamespace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionNamespace) Reset() {
	*x = SessionNamespace{}
	mi := &file_mnemosyne_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionNamespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionNamespace) ProtoMessage() {}

func (x *SessionNamespace) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionNamespace.ProtoReflect.Descriptor instead.
func (*SessionNamespace) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *SessionNamespace) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *SessionNamespace) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type MemoryLink struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TargetId        string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`                               // Target memory ID
	LinkType        LinkType               `protobuf:"varint,2,opt,name=link_type,json=linkType,proto3,enum=mnemosyne.v1.LinkType" json:"link_type,omitempty"`   // Relationship type
	Strength        float32                `protobuf:"fixed32,3,opt,name=strength,proto3" json:"strength,omitempty"`                                             // 0.0-1.0
	Reason          string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`                                                   // Why this link exists
	CreatedAt       uint64                 `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                           // Unix timestamp
	LastTraversedAt *uint64                `protobuf:"varint,6,opt,name=last_traversed_at,json=lastTraversedAt,proto3,oneof" json:"last_traversed_at,omitempty"` // Last access time
	UserCreated     bool                   `protobuf:"varint,7,opt,name=user_created,json=userCreated,proto3" json:"user_created,omitempty"`                     // User links don't decay
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MemoryLink) Reset() {
	*x = MemoryLink{}
	mi := &file_mnemosyne_v1_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryLink) ProtoMessage() {}

func (x *MemoryLink) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryLink.ProtoReflect.Descriptor instead.
func (*MemoryLink) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *MemoryLink) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *MemoryLink) GetLinkType() LinkType {
	if x != nil {
		return x.LinkType
	}
	return LinkType_LINK_TYPE_UNSPECIFIED
}

func (x *MemoryLink) GetStrength() float32 {
	if x != nil {
		return x.Strength
	}
	return 0
}

func (x *MemoryLink) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *MemoryLink) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *MemoryLink) GetLastTraversedAt() uint64 {
	if x != nil && x.LastTraversedAt != nil {
		return *x.LastTraversedAt
	}
	return 0
}

func (x *MemoryLink) GetUserCreated() bool {
	if x != nil {
		return x.UserCreated
	}
	return false
}

type MemoryNote struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity
	Id        string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Namespace *Namespace `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	CreatedAt uint64     `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix timestamp
	UpdatedAt uint64     `protobuf:"varint,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // Unix timestamp
	// Content
	Content  string   `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	Summary  string   `protobuf:"bytes,6,opt,name=summary,proto3" json:"summary,omitempty"`
	Keywords []string `protobuf:"bytes,7,rep,name=keywords,proto3" json:"keywords,omitempty"`
	Tags     []string `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	Context  string   `protobuf:"bytes,9,opt,name=context,proto3" json:"context,omitempty"` // Additional context
	// Classification
	MemoryType MemoryType `protobuf:"varint,10,opt,name=memory_type,json=memoryType,proto3,enum=mnemosyne.v1.MemoryType" json:"memory_type,omitempty"`
	Importance uint32     `protobuf:"varint,11,opt,name=importance,proto3" json:"importance,omitempty"`  // 1-10
	Confidence float32    `protobuf:"fixed32,12,opt,name=confidence,proto3" json:"confidence,omitempty"` // 0.0-1.0
	// Relationships
	Links           []*MemoryLink `protobuf:"bytes,13,rep,name=links,proto3" json:"links,omitempty"`
	RelatedFiles    []string      `protobuf:"bytes,14,rep,name=related_files,json=relatedFiles,proto3" json:"related_files,omitempty"`
	RelatedEntities []string      `protobuf:"bytes,15,rep,name=related_entities,json=relatedEntities,proto3" json:"related_entities,omitempty"`
	// Access tracking
	AccessCount    uint64 `protobuf:"varint,16,opt,name=access_count,json=accessCount,proto3" json:"access_count,omitempty"`
	LastAccessedAt uint64 `protobuf:"varint,17,opt,name=last_accessed_at,json=lastAccessedAt,proto3" json:"last_accessed_at,omitempty"`
	// Lifecycle
	ExpiresAt    *uint64 `protobuf:"varint,18,opt,name=expires_at,json=expiresAt,proto3,oneof" json:"expires_at,omitempty"` // Optional expiration
	IsArchived   bool    `protobuf:"varint,19,opt,name=is_archived,json=isArchived,proto3" json:"is_archived,omitempty"`
	SupersededBy *string `protobuf:"bytes,20,opt,name=superseded_by,json=supersededBy,proto3,oneof" json:"superseded_by,omitempty"` // Memory ID
	// Embeddings
	Embedding      []float32 `protobuf:"fixed32,21,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`                        // Vector embedding (768d or 1536d)
	EmbeddingModel string    `protobuf:"bytes,22,opt,name=embedding_model,json=embeddingModel,proto3" json:"embedding_model,omitempty"` // Model name
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MemoryNote) Reset() {
	*x = MemoryNote{}
	mi := &file_mnemosyne_v1_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryNote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryNote) ProtoMessage() {}

func (x *MemoryNote) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryNote.ProtoReflect.Descriptor instead.
func (*MemoryNote) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *MemoryNote) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MemoryNote) GetNamespace() *Namespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *MemoryNote) GetCreatedAt() uint64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *MemoryNote) GetUpdatedAt() uint64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *MemoryNote) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MemoryNote) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *MemoryNote) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *MemoryNote) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *MemoryNote) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

func (x *MemoryNote) GetMemoryType() MemoryType {
	if x != nil {
		return x.MemoryType
	}
	return MemoryType_MEMORY_TYPE_UNSPECIFIED
}

func (x *MemoryNote) GetImportance() uint32 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *MemoryNote) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *MemoryNote) GetLinks() []*MemoryLink {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *MemoryNote) GetRelatedFiles() []string {
	if x != nil {
		return x.RelatedFiles
	}
	return nil
}

func (x *MemoryNote) GetRelatedEntities() []string {
	if x != nil {
		return x.RelatedEntities
	}
	return nil
}

func (x *MemoryNote) GetAccessCount() uint64 {
	if x != nil {
		return x.AccessCount
	}
	return 0
}

func (x *MemoryNote) GetLastAccessedAt() uint64 {
	if x != nil {
		return x.LastAccessedAt
	}
	return 0
}

func (x *MemoryNote) GetExpiresAt() uint64 {
	if x != nil && x.ExpiresAt != nil {
		return *x.ExpiresAt
	}
	return 0
}

func (x *MemoryNote) GetIsArchived() bool {
	if x != nil {
		return x.IsArchived
	}
	return false
}

func (x *MemoryNote) GetSupersededBy() string {
	if x != nil && x.SupersededBy != nil {
		return *x.SupersededBy
	}
	return ""
}

func (x *MemoryNote) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *MemoryNote) GetEmbeddingModel() string {
	if x != nil {
		return x.EmbeddingModel
	}
	return ""
}

type SearchQuery struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Query           string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`                                                                     // Search text
	Namespace       *Namespace             `protobuf:"bytes,2,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`                                                       // Filter by namespace
	MemoryTypes     []MemoryType           `protobuf:"varint,3,rep,packed,name=memory_types,json=memoryTypes,proto3,enum=mnemosyne.v1.MemoryType" json:"memory_types,omitempty"` // Filter by types
	Tags            []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`                                                                       // Filter by tags
	MinImportance   *uint32                `protobuf:"varint,5,opt,name=min_importance,json=minImportance,proto3,oneof" json:"min_importance,omitempty"`                         // Minimum importance threshold
	MaxResults      uint32                 `protobuf:"varint,6,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"`                                        // Limit results
	IncludeArchived bool                   `protobuf:"varint,7,opt,name=include_archived,json=includeArchived,proto3" json:"include_archived,omitempty"`                         // Include archived memories
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchQuery) Reset() {
	*x = SearchQuery{}
	mi := &file_mnemosyne_v1_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchQuery) ProtoMessage() {}

func (x *SearchQuery) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchQuery.ProtoReflect.Descriptor instead.
func (*SearchQuery) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_types_proto_rawDescGZIP(), []int{7}
}

func (x *SearchQuery) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchQuery) GetNamespace() *Namespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *SearchQuery) GetMemoryTypes() []MemoryType {
	if x != nil {
		return x.MemoryTypes
	}
	return nil
}

func (x *SearchQuery) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *SearchQuery) GetMinImportance() uint32 {
	if x != nil && x.MinImportance != nil {
		return *x.MinImportance
	}
	return 0
}

func (x *SearchQuery) GetMaxResults() uint32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

func (x *SearchQuery) GetIncludeArchived() bool {
	if x != nil {
		return x.IncludeArchived
	}
	return false
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memory        *MemoryNote            `protobuf:"bytes,1,opt,name=memory,proto3" json:"memory,omitempty"`                                            // The memory note
	Score         float32                `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`                                            // Hybrid score (0.0-1.0)
	SemanticScore *float32               `protobuf:"fixed32,3,opt,name=semantic_score,json=semanticScore,proto3,oneof" json:"semantic_score,omitempty"` // Semantic similarity
	FtsScore      *float32               `protobuf:"fixed32,4,opt,name=fts_score,json=ftsScore,proto3,oneof" json:"fts_score,omitempty"`                // Full-text search score
	GraphScore    *float32               `protobuf:"fixed32,5,opt,name=graph_score,json=graphScore,proto3,oneof" json:"graph_score,omitempty"`          // Graph proximity score
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_mnemosyne_v1_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_types_proto_rawDescGZIP(), []int{8}
}

func (x *SearchResult) GetMemory() *MemoryNote {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *SearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SearchResult) GetSemanticScore() float32 {
	if x != nil && x.SemanticScore != nil {
		return *x.SemanticScore
	}
	return 0
}

func (x *SearchResult) GetFtsScore() float32 {
	if x != nil && x.FtsScore != nil {
		return *x.FtsScore
	}
	return 0
}

func (x *SearchResult) GetGraphScore() float32 {
	if x != nil && x.GraphScore != nil {
		return *x.GraphScore
	}
	return 0
}

type ProjectMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	Config        map[string]string      `protobuf:"bytes,5,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Key-value config from CLAUDE.md
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectMetadata) Reset() {
	*x = ProjectMetadata{}
	mi := &file_mnemosyne_v1_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectMetadata) ProtoMessage() {}

func (x *ProjectMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectMetadata.ProtoReflect.Descriptor instead.
func (*ProjectMetadata) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_types_proto_rawDescGZIP(), []int{9}
}

func (x *ProjectMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProjectMetadata) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ProjectMetadata) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ProjectMetadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ProjectMetadata) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

type JobReport struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MemoriesProcessed uint32                 `protobuf:"varint,1,opt,name=memories_processed,json=memoriesProcessed,proto3" json:"memories_processed,omitempty"`
	MemoriesUpdated   uint32                 `protobuf:"varint,2,opt,name=memories_updated,json=memoriesUpdated,proto3" json:"memories_updated,omitempty"`
	Errors            []string               `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	DurationMs        uint64                 `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *JobReport) Reset() {
	*x = JobReport{}
	mi := &file_mnemosyne_v1_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobReport) ProtoMessage() {}

func (x *JobReport) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobReport.ProtoReflect.Descriptor instead.
func (*JobReport) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_types_proto_rawDescGZIP(), []int{10}
}

func (x *JobReport) GetMemoriesProcessed() uint32 {
	if x != nil {
		return x.MemoriesProcessed
	}
	return 0
}

func (x *JobReport) GetMemoriesUpdated() uint32 {
	if x != nil {
		return x.MemoriesUpdated
	}
	return 0
}

func (x *JobReport) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *JobReport) GetDurationMs() uint64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type SupervisionConfig struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	MaxRestarts         uint32                 `protobuf:"varint,1,opt,name=max_restarts,json=maxRestarts,proto3" json:"max_restarts,omitempty"`                     // Default: 3
	RestartWindowSecs   uint64                 `protobuf:"varint,2,opt,name=restart_window_secs,json=restartWindowSecs,proto3" json:"restart_window_secs,omitempty"` // Default: 60
	EnableSubAgents     bool                   `protobuf:"varint,3,opt,name=enable_sub_agents,json=enableSubAgents,proto3" json:"enable_sub_agents,omitempty"`
	MaxConcurrentAgents uint32                 `protobuf:"varint,4,opt,name=max_concurrent_agents,json=maxConcurrentAgents,proto3" json:"max_concurrent_agents,omitempty"` // Default: 4
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SupervisionConfig) Reset() {
	*x = SupervisionConfig{}
	mi := &file_mnemosyne_v1_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SupervisionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SupervisionConfig) ProtoMessage() {}

func (x *SupervisionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SupervisionConfig.ProtoReflect.Descriptor instead.
func (*SupervisionConfig) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_types_proto_rawDescGZIP(), []int{11}
}

func (x *SupervisionConfig) GetMaxRestarts() uint32 {
	if x != nil {
		return x.MaxRestarts
	}
	return 0
}

func (x *SupervisionConfig) GetRestartWindowSecs() uint64 {
	if x != nil {
		return x.RestartWindowSecs
	}
	return 0
}

func (x *SupervisionConfig) GetEnableSubAgents() bool {
	if x != nil {
		return x.EnableSubAgents
	}
	return false
}

func (x *SupervisionConfig) GetMaxConcurrentAgents() uint32 {
	if x != nil {
		return x.MaxConcurrentAgents
	}
	return 0
}

type AgentInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentId         string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentType       string                 `protobuf:"bytes,2,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"` // orchestrator, optimizer, reviewer, executor
	State           AgentState             `protobuf:"varint,3,opt,name=state,proto3,enum=mnemosyne.v1.AgentState" json:"state,omitempty"`
	CurrentWorkItem *string                `protobuf:"bytes,4,opt,name=current_work_item,json=currentWorkItem,proto3,oneof" json:"current_work_item,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_mnemosyne_v1_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_types_proto_rawDescGZIP(), []int{12}
}

func (x *AgentInfo) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentInfo) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *AgentInfo) GetState() AgentState {
	if x != nil {
		return x.State
	}
	return AgentState_AGENT_STATE_UNSPECIFIED
}

func (x *AgentInfo) GetCurrentWorkItem() string {
	if x != nil && x.CurrentWorkItem != nil {
		return *x.CurrentWorkItem
	}
	return ""
}

type WorkItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Priority      uint32                 `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	Dependencies  []string               `protobuf:"bytes,4,rep,name=dependencies,proto3" json:"dependencies,omitempty"` // Work item IDs
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkItem) Reset() {
	*x = WorkItem{}
	mi := &file_mnemosyne_v1_types_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkItem) ProtoMessage() {}

func (x *WorkItem) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_types_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkItem.ProtoReflect.Descriptor instead.
func (*WorkItem) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_types_proto_rawDescGZIP(), []int{13}
}

func (x *WorkItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WorkItem) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *WorkItem) GetDependencies() []string {
	if x != nil {
		return x.Dependencies
	}
	return nil
}

func (x *WorkItem) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type Stats struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TotalMemories   uint64                 `protobuf:"varint,1,opt,name=total_memories,json=totalMemories,proto3" json:"total_memories,omitempty"`
	TotalLinks      uint64                 `protobuf:"varint,2,opt,name=total_links,json=totalLinks,proto3" json:"total_links,omitempty"`
	NamespacesCount uint64                 `protobuf:"varint,3,opt,name=namespaces_count,json=namespacesCount,proto3" json:"namespaces_count,omitempty"`
	MemoriesByType  map[string]uint64      `protobuf:"bytes,4,rep,name=memories_by_type,json=memoriesByType,proto3" json:"memories_by_type,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_mnemosyne_v1_types_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_types_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_types_proto_rawDescGZIP(), []int{14}
}

func (x *Stats) GetTotalMemories() uint64 {
	if x != nil {
		return x.TotalMemories
	}
	return 0
}

func (x *Stats) GetTotalLinks() uint64 {
	if x != nil {
		return x.TotalLinks
	}
	return 0
}

func (x *Stats) GetNamespacesCount() uint64 {
	if x != nil {
		return x.NamespacesCount
	}
	return 0
}

func (x *Stats) GetMemoriesByType() map[string]uint64 {
	if x != nil {
		return x.MemoriesByType
	}
	return nil
}

type Metrics struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	UptimeSeconds        uint64                 `protobuf:"varint,1,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	RequestsTotal        uint64                 `protobuf:"varint,2,opt,name=requests_total,json=requestsTotal,proto3" json:"requests_total,omitempty"`
	RequestsErrors       uint64                 `protobuf:"varint,3,opt,name=requests_errors,json=requestsErrors,proto3" json:"requests_errors,omitempty"`
	RequestDurationAvgMs float64                `protobuf:"fixed64,4,opt,name=request_duration_avg_ms,json=requestDurationAvgMs,proto3" json:"request_duration_avg_ms,omitempty"`
	StorageOpsTotal      uint64                 `protobuf:"varint,5,opt,name=storage_ops_total,json=storageOpsTotal,proto3" json:"storage_ops_total,omitempty"`
	MemoryUsageBytes     uint64                 `protobuf:"varint,6,opt,name=memory_usage_bytes,json=memoryUsageBytes,proto3" json:"memory_usage_bytes,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_mnemosyne_v1_types_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_types_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_types_proto_rawDescGZIP(), []int{15}
}

func (x *Metrics) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *Metrics) GetRequestsTotal() uint64 {
	if x != nil {
		return x.RequestsTotal
	}
	return 0
}

func (x *Metrics) GetRequestsErrors() uint64 {
	if x != nil {
		return x.RequestsErrors
	}
	return 0
}

func (x *Metrics) GetRequestDurationAvgMs() float64 {
	if x != nil {
		return x.RequestDurationAvgMs
	}
	return 0
}

func (x *Metrics) GetStorageOpsTotal() uint64 {
	if x != nil {
		return x.StorageOpsTotal
	}
	return 0
}

func (x *Metrics) GetMemoryUsageBytes() uint64 {
	if x != nil {
		return x.MemoryUsageBytes
	}
	return 0
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Components    map[string]string      `protobuf:"bytes,3,rep,name=components,proto3" json:"components,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Component name -> status
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_mnemosyne_v1_types_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_types_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_types_proto_rawDescGZIP(), []int{16}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetComponents() map[string]string {
	if x != nil {
		return x.Components
	}
	return nil
}

type ModelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Dimension     uint32                 `protobuf:"varint,3,opt,name=dimension,proto3" json:"dimension,omitempty"`
	Local         bool                   `protobuf:"varint,4,opt,name=local,proto3" json:"local,omitempty"` // True if local, false if remote API
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModelInfo) Reset() {
	*x = ModelInfo{}
	mi := &file_mnemosyne_v1_types_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModelInfo) ProtoMessage() {}

func (x *ModelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_types_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModelInfo.ProtoReflect.Descriptor instead.
func (*ModelInfo) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_types_proto_rawDescGZIP(), []int{17}
}

func (x *ModelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ModelInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ModelInfo) GetDimension() uint32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

func (x *ModelInfo) GetLocal() bool {
	if x != nil {
		return x.Local
	}
	return false
}

type EmbeddingResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"` // Index in original batch
	Embedding     []float32              `protobuf:"fixed32,2,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	Error         *string                `protobuf:"bytes,3,opt,name=error,proto3,oneof" json:"error,omitempty"` // If generation failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbeddingResult) Reset() {
	*x = EmbeddingResult{}
	mi := &file_mnemosyne_v1_types_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbeddingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbeddingResult) ProtoMessage() {}

func (x *EmbeddingResult) ProtoReflect() protoreflect.Message {
	mi := &file_mnemosyne_v1_types_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbeddingResult.ProtoReflect.Descriptor instead.
func (*EmbeddingResult) Descriptor() ([]byte, []int) {
	return file_mnemosyne_v1_types_proto_rawDescGZIP(), []int{18}
}

func (x *EmbeddingResult) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *EmbeddingResult) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

func (x *EmbeddingResult) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

var File_mnemosyne_v1_types_proto protoreflect.FileDescriptor

const file_mnemosyne_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x18mnemosyne/v1/types.proto\x12\fmnemosyne.v1\"\x1a\n" +
	"\bMemoryId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc9\x01\n" +
	"\tNamespace\x127\n" +
	"\x06global\x18\x01 \x01(\v2\x1d.mnemosyne.v1.GlobalNamespaceH\x00R\x06global\x12:\n" +
	"\aproject\x18\x02 \x01(\v2\x1e.mnemosyne.v1.ProjectNamespaceH\x00R\aproject\x12:\n" +
	"\asession\x18\x03 \x01(\v2\x1e.mnemosyne.v1.SessionNamespaceH\x00R\asessionB\v\n" +
	"\tnamespace\"\x11\n" +
	"\x0fGlobalNamespace\"&\n" +
	"\x10ProjectNamespace\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"K\n" +
	"\x10SessionNamespace\x12\x18\n" +
	"\aproject\x18\x01 \x01(\tR\aproject\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\"\x9b\x02\n" +
	"\n" +
	"MemoryLink\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x123\n" +
	"\tlink_type\x18\x02 \x01(\x0e2\x16.mnemosyne.v1.LinkTypeR\blinkType\x12\x1a\n" +
	"\bstrength\x18\x03 \x01(\x02R\bstrength\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x04R\tcreatedAt\x12/\n" +
	"\x11last_traversed_at\x18\x06 \x01(\x04H\x00R\x0flastTraversedAt\x88\x01\x01\x12!\n" +
	"\fuser_created\x18\a \x01(\bR\vuserCreatedB\x14\n" +
	"\x12_last_traversed_at\"\xae\x06\n" +
	"\n" +
	"MemoryNote\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x125\n" +
	"\tnamespace\x18\x02 \x01(\v2\x17.mnemosyne.v1.NamespaceR\tnamespace\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x04R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\x04R\tupdatedAt\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x18\n" +
	"\asummary\x18\x06 \x01(\tR\asummary\x12\x1a\n" +
	"\bkeywords\x18\a \x03(\tR\bkeywords\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12\x18\n" +
	"\acontext\x18\t \x01(\tR\acontext\x129\n" +
	"\vmemory_type\x18\n" +
	" \x01(\x0e2\x18.mnemosyne.v1.MemoryTypeR\n" +
	"memoryType\x12\x1e\n" +
	"\n" +
	"importance\x18\v \x01(\rR\n" +
	"importance\x12\x1e\n" +
	"\n" +
	"confidence\x18\f \x01(\x02R\n" +
	"confidence\x12.\n" +
	"\x05links\x18\r \x03(\v2\x18.mnemosyne.v1.MemoryLinkR\x05links\x12#\n" +
	"\rrelated_files\x18\x0e \x03(\tR\frelatedFiles\x12)\n" +
	"\x10related_entities\x18\x0f \x03(\tR\x0frelatedEntities\x12!\n" +
	"\faccess_count\x18\x10 \x01(\x04R\vaccessCount\x12(\n" +
	"\x10last_accessed_at\x18\x11 \x01(\x04R\x0elastAccessedAt\x12\"\n" +
	"\n" +
	"expires_at\x18\x12 \x01(\x04H\x00R\texpiresAt\x88\x01\x01\x12\x1f\n" +
	"\vis_archived\x18\x13 \x01(\bR\n" +
	"isArchived\x12(\n" +
	"\rsuperseded_by\x18\x14 \x01(\tH\x01R\fsupersededBy\x88\x01\x01\x12\x1c\n" +
	"\tembedding\x18\x15 \x03(\x02R\tembedding\x12'\n" +
	"\x0fembedding_model\x18\x16 \x01(\tR\x0eembeddingModelB\r\n" +
	"\v_expires_atB\x10\n" +
	"\x0e_superseded_by\"\xc9\x02\n" +
	"\vSearchQuery\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12:\n" +
	"\tnamespace\x18\x02 \x01(\v2\x17.mnemosyne.v1.NamespaceH\x00R\tnamespace\x88\x01\x01\x12;\n" +
	"\fmemory_types\x18\x03 \x03(\x0e2\x18.mnemosyne.v1.MemoryTypeR\vmemoryTypes\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12*\n" +
	"\x0emin_importance\x18\x05 \x01(\rH\x01R\rminImportance\x88\x01\x01\x12\x1f\n" +
	"\vmax_results\x18\x06 \x01(\rR\n" +
	"maxResults\x12)\n" +
	"\x10include_archived\x18\a \x01(\bR\x0fincludeArchivedB\f\n" +
	"\n" +
	"_namespaceB\x11\n" +
	"\x0f_min_importance\"\xfb\x01\n" +
	"\fSearchResult\x120\n" +
	"\x06memory\x18\x01 \x01(\v2\x18.mnemosyne.v1.MemoryNoteR\x06memory\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x02R\x05score\x12*\n" +
	"\x0esemantic_score\x18\x03 \x01(\x02H\x00R\rsemanticScore\x88\x01\x01\x12 \n" +
	"\tfts_score\x18\x04 \x01(\x02H\x01R\bftsScore\x88\x01\x01\x12$\n" +
	"\vgraph_score\x18\x05 \x01(\x02H\x02R\n" +
	"graphScore\x88\x01\x01B\x11\n" +
	"\x0f_semantic_scoreB\f\n" +
	"\n" +
	"_fts_scoreB\x0e\n" +
	"\f_graph_score\"\x82\x02\n" +
	"\x0fProjectMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x00R\vdescription\x88\x01\x01\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12A\n" +
	"\x06config\x18\x05 \x03(\v2).mnemosyne.v1.ProjectMetadata.ConfigEntryR\x06config\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x0e\n" +
	"\f_description\"\x9e\x01\n" +
	"\tJobReport\x12-\n" +
	"\x12memories_processed\x18\x01 \x01(\rR\x11memoriesProcessed\x12)\n" +
	"\x10memories_updated\x18\x02 \x01(\rR\x0fmemoriesUpdated\x12\x16\n" +
	"\x06errors\x18\x03 \x03(\tR\x06errors\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x04R\n" +
	"durationMs\"\xc6\x01\n" +
	"\x11SupervisionConfig\x12!\n" +
	"\fmax_restarts\x18\x01 \x01(\rR\vmaxRestarts\x12.\n" +
	"\x13restart_window_secs\x18\x02 \x01(\x04R\x11restartWindowSecs\x12*\n" +
	"\x11enable_sub_agents\x18\x03 \x01(\bR\x0fenableSubAgents\x122\n" +
	"\x15max_concurrent_agents\x18\x04 \x01(\rR\x13maxConcurrentAgents\"\xbc\x01\n" +
	"\tAgentInfo\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x02 \x01(\tR\tagentType\x12.\n" +
	"\x05state\x18\x03 \x01(\x0e2\x18.mnemosyne.v1.AgentStateR\x05state\x12/\n" +
	"\x11current_work_item\x18\x04 \x01(\tH\x00R\x0fcurrentWorkItem\x88\x01\x01B\x14\n" +
	"\x12_current_work_item\"\xfb\x01\n" +
	"\bWorkItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\rR\bpriority\x12\"\n" +
	"\fdependencies\x18\x04 \x03(\tR\fdependencies\x12@\n" +
	"\bmetadata\x18\x05 \x03(\v2$.mnemosyne.v1.WorkItem.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x90\x02\n" +
	"\x05Stats\x12%\n" +
	"\x0etotal_memories\x18\x01 \x01(\x04R\rtotalMemories\x12\x1f\n" +
	"\vtotal_links\x18\x02 \x01(\x04R\n" +
	"totalLinks\x12)\n" +
	"\x10namespaces_count\x18\x03 \x01(\x04R\x0fnamespacesCount\x12Q\n" +
	"\x10memories_by_type\x18\x04 \x03(\v2'.mnemosyne.v1.Stats.MemoriesByTypeEntryR\x0ememoriesByType\x1aA\n" +
	"\x13MemoriesByTypeEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x04R\x05value:\x028\x01\"\x91\x02\n" +
	"\aMetrics\x12%\n" +
	"\x0euptime_seconds\x18\x01 \x01(\x04R\ruptimeSeconds\x12%\n" +
	"\x0erequests_total\x18\x02 \x01(\x04R\rrequestsTotal\x12'\n" +
	"\x0frequests_errors\x18\x03 \x01(\x04R\x0erequestsErrors\x125\n" +
	"\x17request_duration_avg_ms\x18\x04 \x01(\x01R\x14requestDurationAvgMs\x12*\n" +
	"\x11storage_ops_total\x18\x05 \x01(\x04R\x0fstorageOpsTotal\x12,\n" +
	"\x12memory_usage_bytes\x18\x06 \x01(\x04R\x10memoryUsageBytes\"\xdb\x01\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12Q\n" +
	"\n" +
	"components\x18\x03 \x03(\v21.mnemosyne.v1.HealthCheckResponse.ComponentsEntryR\n" +
	"components\x1a=\n" +
	"\x0fComponentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"u\n" +
	"\tModelInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1c\n" +
	"\tdimension\x18\x03 \x01(\rR\tdimension\x12\x14\n" +
	"\x05local\x18\x04 \x01(\bR\x05local\"j\n" +
	"\x0fEmbeddingResult\x12\x14\n" +
	"\x05index\x18\x01 \x01(\rR\x05index\x12\x1c\n" +
	"\tembedding\x18\x02 \x03(\x02R\tembedding\x12\x19\n" +
	"\x05error\x18\x03 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error*\xa0\x04\n" +
	"\n" +
	"MemoryType\x12\x1b\n" +
	"\x17MEMORY_TYPE_UNSPECIFIED\x10\x00\x12%\n" +
	"!MEMORY_TYPE_ARCHITECTURE_DECISION\x10\x01\x12\x1c\n" +
	"\x18MEMORY_TYPE_CODE_PATTERN\x10\x02\x12\x17\n" +
	"\x13MEMORY_TYPE_BUG_FIX\x10\x03\x12\x1d\n" +
	"\x19MEMORY_TYPE_CONFIGURATION\x10\x04\x12\x1a\n" +
	"\x16MEMORY_TYPE_CONSTRAINT\x10\x05\x12\x16\n" +
	"\x12MEMORY_TYPE_ENTITY\x10\x06\x12\x17\n" +
	"\x13MEMORY_TYPE_INSIGHT\x10\a\x12\x19\n" +
	"\x15MEMORY_TYPE_REFERENCE\x10\b\x12\x1a\n" +
	"\x16MEMORY_TYPE_PREFERENCE\x10\t\x12\x14\n" +
	"\x10MEMORY_TYPE_TASK\x10\n" +
	"\x12\x1b\n" +
	"\x17MEMORY_TYPE_AGENT_EVENT\x10\v\x12\x1c\n" +
	"\x18MEMORY_TYPE_CONSTITUTION\x10\f\x12\x1c\n" +
	"\x18MEMORY_TYPE_FEATURE_SPEC\x10\r\x12#\n" +
	"\x1fMEMORY_TYPE_IMPLEMENTATION_PLAN\x10\x0e\x12\x1e\n" +
	"\x1aMEMORY_TYPE_TASK_BREAKDOWN\x10\x0f\x12!\n" +
	"\x1dMEMORY_TYPE_QUALITY_CHECKLIST\x10\x10\x12\x1d\n" +
	"\x19MEMORY_TYPE_CLARIFICATION\x10\x11*\xf6\x01\n" +
	"\bLinkType\x12\x19\n" +
	"\x15LINK_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11LINK_TYPE_EXTENDS\x10\x01\x12\x19\n" +
	"\x15LINK_TYPE_BUILDS_UPON\x10\x02\x12\x19\n" +
	"\x15LINK_TYPE_CONTRADICTS\x10\x03\x12\x18\n" +
	"\x14LINK_TYPE_IMPLEMENTS\x10\x04\x12\x18\n" +
	"\x14LINK_TYPE_REFERENCES\x10\x05\x12\x1b\n" +
	"\x17LINK_TYPE_REFERENCED_BY\x10\x06\x12\x17\n" +
	"\x13LINK_TYPE_CLARIFIES\x10\a\x12\x18\n" +
	"\x14LINK_TYPE_SUPERSEDES\x10\b*\xad\x01\n" +
	"\x15ConsolidationDecision\x12&\n" +
	"\"CONSOLIDATION_DECISION_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cCONSOLIDATION_DECISION_MERGE\x10\x01\x12$\n" +
	" CONSOLIDATION_DECISION_SUPERSEDE\x10\x02\x12$\n" +
	" CONSOLIDATION_DECISION_KEEP_BOTH\x10\x03*\x89\x01\n" +
	"\n" +
	"AgentState\x12\x1b\n" +
	"\x17AGENT_STATE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10AGENT_STATE_IDLE\x10\x01\x12\x17\n" +
	"\x13AGENT_STATE_RUNNING\x10\x02\x12\x17\n" +
	"\x13AGENT_STATE_BLOCKED\x10\x03\x12\x16\n" +
	"\x12AGENT_STATE_FAILED\x10\x04B6Z4github.com/rand/pedantic-raven/internal/mnemosyne/pbb\x06proto3"

var (
	file_mnemosyne_v1_types_proto_rawDescOnce sync.Once
	file_mnemosyne_v1_types_proto_rawDescData []byte
)

func file_mnemosyne_v1_types_proto_rawDescGZIP() []byte {
	file_mnemosyne_v1_types_proto_rawDescOnce.Do(func() {
		file_mnemosyne_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mnemosyne_v1_types_proto_rawDesc), len(file_mnemosyne_v1_types_proto_rawDesc)))
	})
	return file_mnemosyne_v1_types_proto_rawDescData
}

var file_mnemosyne_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_mnemosyne_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_mnemosyne_v1_types_proto_goTypes = []any{
	(MemoryType)(0),             // 0: mnemosyne.v1.MemoryType
	(LinkType)(0),               // 1: mnemosyne.v1.LinkType
	(ConsolidationDecision)(0),  // 2: mnemosyne.v1.ConsolidationDecision
	(AgentState)(0),             // 3: mnemosyne.v1.AgentState
	(*MemoryId)(nil),            // 4: mnemosyne.v1.MemoryId
	(*Namespace)(nil),           // 5: mnemosyne.v1.Namespace
	(*GlobalNamespace)(nil),     // 6: mnemosyne.v1.GlobalNamespace
	(*ProjectNamespace)(nil),    // 7: mnemosyne.v1.ProjectNamespace
	(*SessionNamespace)(nil),    // 8: mnemosyne.v1.SessionNamespace
	(*MemoryLink)(nil),          // 9: mnemosyne.v1.MemoryLink
	(*MemoryNote)(nil),          // 10: mnemosyne.v1.MemoryNote
	(*SearchQuery)(nil),         // 11: mnemosyne.v1.SearchQuery
	(*SearchResult)(nil),        // 12: mnemosyne.v1.SearchResult
	(*ProjectMetadata)(nil),     // 13: mnemosyne.v1.ProjectMetadata
	(*JobReport)(nil),           // 14: mnemosyne.v1.JobReport
	(*SupervisionConfig)(nil),   // 15: mnemosyne.v1.SupervisionConfig
	(*AgentInfo)(nil),           // 16: mnemosyne.v1.AgentInfo
	(*WorkItem)(nil),            // 17: mnemosyne.v1.WorkItem
	(*Stats)(nil),               // 18: mnemosyne.v1.Stats
	(*Metrics)(nil),             // 19: mnemosyne.v1.Metrics
	(*HealthCheckResponse)(nil), // 20: mnemosyne.v1.HealthCheckResponse
	(*ModelInfo)(nil),           // 21: mnemosyne.v1.ModelInfo
	(*EmbeddingResult)(nil),     // 22: mnemosyne.v1.EmbeddingResult
	nil,                         // 23: mnemosyne.v1.ProjectMetadata.ConfigEntry
	nil,                         // 24: mnemosyne.v1.WorkItem.MetadataEntry
	nil,                         // 25: mnemosyne.v1.Stats.MemoriesByTypeEntry
	nil,                         // 26: mnemosyne.v1.HealthCheckResponse.ComponentsEntry
}
var file_mnemosyne_v1_types_proto_depIdxs = []int32{
	6,  // 0: mnemosyne.v1.Namespace.global:type_name -> mnemosyne.v1.GlobalNamespace
	7,  // 1: mnemosyne.v1.Namespace.project:type_name -> mnemosyne.v1.ProjectNamespace
	8,  // 2: mnemosyne.v1.Namespace.session:type_name -> mnemosyne.v1.SessionNamespace
	1,  // 3: mnemosyne.v1.MemoryLink.link_type:type_name -> mnemosyne.v1.LinkType
	5,  // 4: mnemosyne.v1.MemoryNote.namespace:type_name -> mnemosyne.v1.Namespace
	0,  // 5: mnemosyne.v1.MemoryNote.memory_type:type_name -> mnemosyne.v1.MemoryType
	9,  // 6: mnemosyne.v1.MemoryNote.links:type_name -> mnemosyne.v1.MemoryLink
	5,  // 7: mnemosyne.v1.SearchQuery.namespace:type_name -> mnemosyne.v1.Namespace
	0,  // 8: mnemosyne.v1.SearchQuery.memory_types:type_name -> mnemosyne.v1.MemoryType
	10, // 9: mnemosyne.v1.SearchResult.memory:type_name -> mnemosyne.v1.MemoryNote
	23, // 10: mnemosyne.v1.ProjectMetadata.config:type_name -> mnemosyne.v1.ProjectMetadata.ConfigEntry
	3,  // 11: mnemosyne.v1.AgentInfo.state:type_name -> mnemosyne.v1.AgentState
	24, // 12: mnemosyne.v1.WorkItem.metadata:type_name -> mnemosyne.v1.WorkItem.MetadataEntry
	25, // 13: mnemosyne.v1.Stats.memories_by_type:type_name -> mnemosyne.v1.Stats.MemoriesByTypeEntry
	26, // 14: mnemosyne.v1.HealthCheckResponse.components:type_name -> mnemosyne.v1.HealthCheckResponse.ComponentsEntry
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_mnemosyne_v1_types_proto_init() }
func file_mnemosyne_v1_types_proto_init() {
	if File_mnemosyne_v1_types_proto != nil {
		return
	}
	file_mnemosyne_v1_types_proto_msgTypes[1].OneofWrappers = []any{
		(*Namespace_Global)(nil),
		(*Namespace_Project)(nil),
		(*Namespace_Session)(nil),
	}
	file_mnemosyne_v1_types_proto_msgTypes[5].OneofWrappers = []any{}
	file_mnemosyne_v1_types_proto_msgTypes[6].OneofWrappers = []any{}
	file_mnemosyne_v1_types_proto_msgTypes[7].OneofWrappers = []any{}
	file_mnemosyne_v1_types_proto_msgTypes[8].OneofWrappers = []any{}
	file_mnemosyne_v1_types_proto_msgTypes[9].OneofWrappers = []any{}
	file_mnemosyne_v1_types_proto_msgTypes[12].OneofWrappers = []any{}
	file_mnemosyne_v1_types_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mnemosyne_v1_types_proto_rawDesc), len(file_mnemosyne_v1_types_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mnemosyne_v1_types_proto_goTypes,
		DependencyIndexes: file_mnemosyne_v1_types_proto_depIdxs,
		EnumInfos:         file_mnemosyne_v1_types_proto_enumTypes,
		MessageInfos:      file_mnemosyne_v1_types_proto_msgTypes,
	}.Build()
	File_mnemosyne_v1_types_proto = out.File
	file_mnemosyne_v1_types_proto_goTypes = nil
	file_mnemosyne_v1_types_proto_depIdxs = nil
}
